// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const getUserByEmail = `SELECT id, email, password_hash, display_name, church_name, timezone, created_at, updated_at FROM users WHERE email = ?`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.DisplayName, &u.ChurchName, &u.Timezone, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

const getUserByID = `SELECT id, email, password_hash, display_name, church_name, timezone, created_at, updated_at FROM users WHERE id = ?`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.DisplayName, &u.ChurchName, &u.Timezone, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

const createUser = `INSERT INTO users (email, password_hash, display_name, church_name, timezone) VALUES (?, ?, ?, ?, ?) RETURNING id, email, password_hash, display_name, church_name, timezone, created_at, updated_at`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
	ChurchName   string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName, arg.ChurchName, arg.Timezone)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.DisplayName, &u.ChurchName, &u.Timezone, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

const upsertUser = `INSERT INTO users (email, password_hash, display_name, church_name, timezone) VALUES (?, ?, ?, ?, ?) ON CONFLICT(email) DO UPDATE SET password_hash = excluded.password_hash, display_name = excluded.display_name, church_name = excluded.church_name, timezone = excluded.timezone, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') RETURNING id, email, password_hash, display_name, church_name, timezone, created_at, updated_at`

func (q *Queries) UpsertUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.Email, arg.PasswordHash, arg.DisplayName, arg.ChurchName, arg.Timezone)
	var u User
	err := row.Scan(&u.ID, &u.Email, &u.PasswordHash, &u.DisplayName, &u.ChurchName, &u.Timezone, &u.CreatedAt, &u.UpdatedAt)
	return u, err
}

const createSession = `INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?) RETURNING token, user_id, expires_at, created_at`

type CreateSessionParams struct {
	Token     string
	UserID    int64
	ExpiresAt string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var s Session
	err := row.Scan(&s.Token, &s.UserID, &s.ExpiresAt, &s.CreatedAt)
	return s, err
}

const getSession = `SELECT token, user_id, expires_at, created_at FROM sessions WHERE token = ? AND expires_at > strftime('%Y-%m-%dT%H:%M:%fZ','now')`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var s Session
	err := row.Scan(&s.Token, &s.UserID, &s.ExpiresAt, &s.CreatedAt)
	return s, err
}

const deleteSession = `DELETE FROM sessions WHERE token = ?`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteExpiredSessions = `DELETE FROM sessions WHERE expires_at <= strftime('%Y-%m-%dT%H:%M:%fZ','now')`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}
