// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: churches.sql

package sqlc

import (
	"context"
)

const createChurch = `-- name: CreateChurch :one
INSERT INTO churches (name, slug, timezone) VALUES (?, ?, ?) RETURNING id, name, slug, timezone, created_at, updated_at
`

type CreateChurchParams struct {
	Name     string `db:"name" json:"name"`
	Slug     string `db:"slug" json:"slug"`
	Timezone string `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error) {
	row := q.db.QueryRowContext(ctx, createChurch, arg.Name, arg.Slug, arg.Timezone)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChurchByID = `-- name: GetChurchByID :one
SELECT id, name, slug, timezone, created_at, updated_at FROM churches WHERE id = ?
`

func (q *Queries) GetChurchByID(ctx context.Context, id int64) (Church, error) {
	row := q.db.QueryRowContext(ctx, getChurchByID, id)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChurchBySlug = `-- name: GetChurchBySlug :one
SELECT id, name, slug, timezone, created_at, updated_at FROM churches WHERE slug = ?
`

func (q *Queries) GetChurchBySlug(ctx context.Context, slug string) (Church, error) {
	row := q.db.QueryRowContext(ctx, getChurchBySlug, slug)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
