// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const listJadwalByKebaktian = `SELECT jp.id, jp.user_id, jp.kebaktian_id, jp.service_type_id, jp.pelayan_id, jp.catatan, jp.confirmed, jp.created_at, jp.updated_at, st.nama AS service_type_nama, st.urutan AS service_type_urutan, j.nama_lengkap AS pelayan_nama FROM jadwal_pelayanan jp JOIN service_types st ON st.id = jp.service_type_id LEFT JOIN pelayan p ON p.id = jp.pelayan_id LEFT JOIN jemaat j ON j.id = p.jemaat_id WHERE jp.kebaktian_id = ? AND jp.user_id = ? ORDER BY st.urutan ASC, st.nama ASC`

type ListJadwalByKebaktianParams struct {
	KebaktianID int64
	UserID      int64
}

func (q *Queries) ListJadwalByKebaktian(ctx context.Context, arg ListJadwalByKebaktianParams) ([]JadwalRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalByKebaktian, arg.KebaktianID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JadwalRow
	for rows.Next() {
		var r JadwalRow
		if err := rows.Scan(
			&r.ID, &r.UserID, &r.KebaktianID, &r.ServiceTypeID, &r.PelayanID,
			&r.Catatan, &r.Confirmed, &r.CreatedAt, &r.UpdatedAt,
			&r.ServiceTypeNama, &r.ServiceTypeUrutan, &r.PelayanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const deleteJadwalByKebaktian = `DELETE FROM jadwal_pelayanan WHERE kebaktian_id = ? AND user_id = ?`

type DeleteJadwalByKebaktianParams struct {
	KebaktianID int64
	UserID      int64
}

func (q *Queries) DeleteJadwalByKebaktian(ctx context.Context, arg DeleteJadwalByKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteJadwalByKebaktian, arg.KebaktianID, arg.UserID)
	return err
}

const createJadwalSlot = `INSERT INTO jadwal_pelayanan (user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed, created_at, updated_at`

type CreateJadwalSlotParams struct {
	UserID        int64
	KebaktianID   int64
	ServiceTypeID int64
	PelayanID     sql.NullInt64
	Catatan       sql.NullString
	Confirmed     int64
}

func (q *Queries) CreateJadwalSlot(ctx context.Context, arg CreateJadwalSlotParams) (JadwalPelayanan, error) {
	row := q.db.QueryRowContext(ctx, createJadwalSlot, arg.UserID, arg.KebaktianID, arg.ServiceTypeID, arg.PelayanID, arg.Catatan, arg.Confirmed)
	var jp JadwalPelayanan
	err := row.Scan(&jp.ID, &jp.UserID, &jp.KebaktianID, &jp.ServiceTypeID, &jp.PelayanID, &jp.Catatan, &jp.Confirmed, &jp.CreatedAt, &jp.UpdatedAt)
	return jp, err
}

const getJadwalSlot = `SELECT id, user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed, created_at, updated_at FROM jadwal_pelayanan WHERE id = ? AND user_id = ?`

type GetJadwalSlotParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetJadwalSlot(ctx context.Context, arg GetJadwalSlotParams) (JadwalPelayanan, error) {
	row := q.db.QueryRowContext(ctx, getJadwalSlot, arg.ID, arg.UserID)
	var jp JadwalPelayanan
	err := row.Scan(&jp.ID, &jp.UserID, &jp.KebaktianID, &jp.ServiceTypeID, &jp.PelayanID, &jp.Catatan, &jp.Confirmed, &jp.CreatedAt, &jp.UpdatedAt)
	return jp, err
}
