// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jadwal.sql

package sqlc

import (
	"context"
)

const createJadwalSlot = `-- name: CreateJadwalSlot :one
INSERT INTO jadwal_pelayanan (church_id, kebaktian_id, service_type_id, pelayan_id, catatan)
VALUES (?, ?, ?, ?, ?)
RETURNING id, church_id, kebaktian_id, service_type_id, pelayan_id, catatan, status, created_at, updated_at
`

type CreateJadwalSlotParams struct {
	ChurchID      int64   `db:"church_id" json:"church_id"`
	KebaktianID   int64   `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID int64   `db:"service_type_id" json:"service_type_id"`
	PelayanID     *int64  `db:"pelayan_id" json:"pelayan_id"`
	Catatan       *string `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateJadwalSlot(ctx context.Context, arg CreateJadwalSlotParams) (JadwalPelayanan, error) {
	row := q.db.QueryRowContext(ctx, createJadwalSlot,
		arg.ChurchID,
		arg.KebaktianID,
		arg.ServiceTypeID,
		arg.PelayanID,
		arg.Catatan,
	)
	var i JadwalPelayanan
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.KebaktianID,
		&i.ServiceTypeID,
		&i.PelayanID,
		&i.Catatan,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKebaktian = `-- name: CreateKebaktian :one
INSERT INTO kebaktian (church_id, nama, tanggal, waktu_mulai, lokasi, tema, pengkhotbah, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, church_id, nama, tanggal, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type CreateKebaktianParams struct {
	ChurchID    int64   `db:"church_id" json:"church_id"`
	Nama        string  `db:"nama" json:"nama"`
	Tanggal     string  `db:"tanggal" json:"tanggal"`
	WaktuMulai  string  `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      *string `db:"lokasi" json:"lokasi"`
	Tema        *string `db:"tema" json:"tema"`
	Pengkhotbah *string `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     *string `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, createKebaktian,
		arg.ChurchID,
		arg.Nama,
		arg.Tanggal,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Tanggal,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJadwalByKebaktian = `-- name: DeleteJadwalByKebaktian :exec
DELETE FROM jadwal_pelayanan WHERE kebaktian_id = ? AND church_id = ?
`

type DeleteJadwalByKebaktianParams struct {
	KebaktianID int64 `db:"kebaktian_id" json:"kebaktian_id"`
	ChurchID    int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeleteJadwalByKebaktian(ctx context.Context, arg DeleteJadwalByKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteJadwalByKebaktian, arg.KebaktianID, arg.ChurchID)
	return err
}

const deleteKebaktian = `-- name: DeleteKebaktian :exec
DELETE FROM kebaktian WHERE id = ? AND church_id = ?
`

type DeleteKebaktianParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteKebaktian, arg.ID, arg.ChurchID)
	return err
}

const getJadwalByKebaktian = `-- name: GetJadwalByKebaktian :many
SELECT jp.id, jp.church_id, jp.kebaktian_id, jp.service_type_id, jp.pelayan_id, jp.catatan, jp.status, jp.created_at, jp.updated_at, st.nama AS service_type_name, st.warna AS service_type_warna,
       p.jemaat_id, j.nama_lengkap AS pelayan_nama
FROM jadwal_pelayanan jp
JOIN service_types st ON st.id = jp.service_type_id
LEFT JOIN pelayan p ON p.id = jp.pelayan_id
LEFT JOIN jemaat j ON j.id = p.jemaat_id
WHERE jp.kebaktian_id = ? AND jp.church_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

type GetJadwalByKebaktianParams struct {
	KebaktianID int64 `db:"kebaktian_id" json:"kebaktian_id"`
	ChurchID    int64 `db:"church_id" json:"church_id"`
}

type GetJadwalByKebaktianRow struct {
	ID               int64   `db:"id" json:"id"`
	ChurchID         int64   `db:"church_id" json:"church_id"`
	KebaktianID      int64   `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID    int64   `db:"service_type_id" json:"service_type_id"`
	PelayanID        *int64  `db:"pelayan_id" json:"pelayan_id"`
	Catatan          *string `db:"catatan" json:"catatan"`
	Status           string  `db:"status" json:"status"`
	CreatedAt        string  `db:"created_at" json:"created_at"`
	UpdatedAt        string  `db:"updated_at" json:"updated_at"`
	ServiceTypeName  string  `db:"service_type_name" json:"service_type_name"`
	ServiceTypeWarna *string `db:"service_type_warna" json:"service_type_warna"`
	JemaatID         *int64  `db:"jemaat_id" json:"jemaat_id"`
	PelayanNama      *string `db:"pelayan_nama" json:"pelayan_nama"`
}

func (q *Queries) GetJadwalByKebaktian(ctx context.Context, arg GetJadwalByKebaktianParams) ([]GetJadwalByKebaktianRow, error) {
	rows, err := q.db.QueryContext(ctx, getJadwalByKebaktian, arg.KebaktianID, arg.ChurchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetJadwalByKebaktianRow{}
	for rows.Next() {
		var i GetJadwalByKebaktianRow
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.KebaktianID,
			&i.ServiceTypeID,
			&i.PelayanID,
			&i.Catatan,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTypeName,
			&i.ServiceTypeWarna,
			&i.JemaatID,
			&i.PelayanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKebaktianByID = `-- name: GetKebaktianByID :one
SELECT id, church_id, nama, tanggal, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE id = ? AND church_id = ?
`

type GetKebaktianByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) GetKebaktianByID(ctx context.Context, arg GetKebaktianByIDParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, getKebaktianByID, arg.ID, arg.ChurchID)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Tanggal,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKebaktianByChurch = `-- name: ListKebaktianByChurch :many
SELECT id, church_id, nama, tanggal, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian
WHERE church_id = ?
  AND tanggal >= ? AND tanggal <= ?
ORDER BY tanggal ASC, waktu_mulai ASC
LIMIT ? OFFSET ?
`

type ListKebaktianByChurchParams struct {
	ChurchID  int64  `db:"church_id" json:"church_id"`
	Tanggal   string `db:"tanggal" json:"tanggal"`
	Tanggal_2 string `db:"tanggal_2" json:"tanggal_2"`
	Limit     int64  `db:"limit" json:"limit"`
	Offset    int64  `db:"offset" json:"offset"`
}

func (q *Queries) ListKebaktianByChurch(ctx context.Context, arg ListKebaktianByChurchParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktianByChurch,
		arg.ChurchID,
		arg.Tanggal,
		arg.Tanggal_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kebaktian{}
	for rows.Next() {
		var i Kebaktian
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.Nama,
			&i.Tanggal,
			&i.WaktuMulai,
			&i.Lokasi,
			&i.Tema,
			&i.Pengkhotbah,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKebaktian = `-- name: UpdateKebaktian :one
UPDATE kebaktian SET
    nama = ?,
    tanggal = ?,
    waktu_mulai = ?,
    lokasi = ?,
    tema = ?,
    pengkhotbah = ?,
    catatan = ?,
    updated_at = datetime('now')
WHERE id = ? AND church_id = ?
RETURNING id, church_id, nama, tanggal, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type UpdateKebaktianParams struct {
	Nama        string  `db:"nama" json:"nama"`
	Tanggal     string  `db:"tanggal" json:"tanggal"`
	WaktuMulai  string  `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      *string `db:"lokasi" json:"lokasi"`
	Tema        *string `db:"tema" json:"tema"`
	Pengkhotbah *string `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     *string `db:"catatan" json:"catatan"`
	ID          int64   `db:"id" json:"id"`
	ChurchID    int64   `db:"church_id" json:"church_id"`
}

func (q *Queries) UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, updateKebaktian,
		arg.Nama,
		arg.Tanggal,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
		arg.ID,
		arg.ChurchID,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Tanggal,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
