// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const getJemaat = `SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE id = ? AND user_id = ?`

type GetJemaatParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetJemaat(ctx context.Context, arg GetJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, getJemaat, arg.ID, arg.UserID)
	return scanJemaat(row)
}

func scanJemaat(row *sql.Row) (Jemaat, error) {
	var j Jemaat
	err := row.Scan(
		&j.ID, &j.UserID, &j.NamaLengkap, &j.NamaPanggilan, &j.JenisKelamin,
		&j.TanggalLahir, &j.TempatLahir, &j.Alamat, &j.NomorTelepon, &j.Email,
		&j.StatusPernikahan, &j.TanggalBaptis, &j.TanggalSidi, &j.KeluargaID,
		&j.Catatan, &j.IsActive, &j.CreatedAt, &j.UpdatedAt,
	)
	return j, err
}

func scanJemaatRows(rows *sql.Rows) ([]Jemaat, error) {
	var items []Jemaat
	for rows.Next() {
		var j Jemaat
		if err := rows.Scan(
			&j.ID, &j.UserID, &j.NamaLengkap, &j.NamaPanggilan, &j.JenisKelamin,
			&j.TanggalLahir, &j.TempatLahir, &j.Alamat, &j.NomorTelepon, &j.Email,
			&j.StatusPernikahan, &j.TanggalBaptis, &j.TanggalSidi, &j.KeluargaID,
			&j.Catatan, &j.IsActive, &j.CreatedAt, &j.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, j)
	}
	return items, rows.Err()
}

const listJemaat = `SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE user_id = ? AND is_active = 1 ORDER BY nama_lengkap ASC LIMIT ? OFFSET ?`

type ListJemaatParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListJemaat(ctx context.Context, arg ListJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaat, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanJemaatRows(rows)
}

const searchJemaat = `SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE user_id = ? AND is_active = 1 AND (nama_lengkap LIKE ? OR nama_panggilan LIKE ?) ORDER BY nama_lengkap ASC LIMIT ? OFFSET ?`

type SearchJemaatParams struct {
	UserID int64
	Query  string
	Limit  int64
	Offset int64
}

func (q *Queries) SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, searchJemaat, arg.UserID, arg.Query, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanJemaatRows(rows)
}

const countJemaat = `SELECT COUNT(*) FROM jemaat WHERE user_id = ? AND is_active = 1`

func (q *Queries) CountJemaat(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJemaat, userID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countJemaatSearch = `SELECT COUNT(*) FROM jemaat WHERE user_id = ? AND is_active = 1 AND (nama_lengkap LIKE ? OR nama_panggilan LIKE ?)`

type CountJemaatSearchParams struct {
	UserID int64
	Query  string
}

func (q *Queries) CountJemaatSearch(ctx context.Context, arg CountJemaatSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJemaatSearch, arg.UserID, arg.Query, arg.Query)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createJemaat = `INSERT INTO jemaat (user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at`

type CreateJemaatParams struct {
	UserID           int64
	NamaLengkap      string
	NamaPanggilan    sql.NullString
	JenisKelamin     sql.NullString
	TanggalLahir     sql.NullString
	TempatLahir      sql.NullString
	Alamat           sql.NullString
	NomorTelepon     sql.NullString
	Email            sql.NullString
	StatusPernikahan sql.NullString
	TanggalBaptis    sql.NullString
	TanggalSidi      sql.NullString
	KeluargaID       sql.NullInt64
	Catatan          sql.NullString
}

func (q *Queries) CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, createJemaat,
		arg.UserID, arg.NamaLengkap, arg.NamaPanggilan, arg.JenisKelamin,
		arg.TanggalLahir, arg.TempatLahir, arg.Alamat, arg.NomorTelepon, arg.Email,
		arg.StatusPernikahan, arg.TanggalBaptis, arg.TanggalSidi, arg.KeluargaID, arg.Catatan,
	)
	return scanJemaat(row)
}

const updateJemaat = `UPDATE jemaat SET nama_lengkap=?, nama_panggilan=?, jenis_kelamin=?, tanggal_lahir=?, tempat_lahir=?, alamat=?, nomor_telepon=?, email=?, status_pernikahan=?, tanggal_baptis=?, tanggal_sidi=?, keluarga_id=?, catatan=?, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND user_id=? RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at`

type UpdateJemaatParams struct {
	NamaLengkap      string
	NamaPanggilan    sql.NullString
	JenisKelamin     sql.NullString
	TanggalLahir     sql.NullString
	TempatLahir      sql.NullString
	Alamat           sql.NullString
	NomorTelepon     sql.NullString
	Email            sql.NullString
	StatusPernikahan sql.NullString
	TanggalBaptis    sql.NullString
	TanggalSidi      sql.NullString
	KeluargaID       sql.NullInt64
	Catatan          sql.NullString
	ID               int64
	UserID           int64
}

func (q *Queries) UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, updateJemaat,
		arg.NamaLengkap, arg.NamaPanggilan, arg.JenisKelamin,
		arg.TanggalLahir, arg.TempatLahir, arg.Alamat, arg.NomorTelepon, arg.Email,
		arg.StatusPernikahan, arg.TanggalBaptis, arg.TanggalSidi, arg.KeluargaID, arg.Catatan,
		arg.ID, arg.UserID,
	)
	return scanJemaat(row)
}

const deactivateJemaat = `UPDATE jemaat SET is_active=0, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND user_id=?`

type DeactivateJemaatParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error {
	_, err := q.db.ExecContext(ctx, deactivateJemaat, arg.ID, arg.UserID)
	return err
}

const listJemaatByKeluarga = `SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE user_id = ? AND keluarga_id = ? AND is_active = 1 ORDER BY nama_lengkap ASC`

type ListJemaatByKeluargaParams struct {
	UserID     int64
	KeluargaID int64
}

func (q *Queries) ListJemaatByKeluarga(ctx context.Context, arg ListJemaatByKeluargaParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaatByKeluarga, arg.UserID, arg.KeluargaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanJemaatRows(rows)
}

const listAllActiveJemaat = `SELECT id, nama_lengkap, nama_panggilan FROM jemaat WHERE user_id = ? AND is_active = 1 ORDER BY nama_lengkap ASC`

type ListAllActiveJemaatRow struct {
	ID            int64          `json:"id"`
	NamaLengkap   string         `json:"nama_lengkap"`
	NamaPanggilan sql.NullString `json:"nama_panggilan"`
}

func (q *Queries) ListAllActiveJemaat(ctx context.Context, userID int64) ([]ListAllActiveJemaatRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveJemaat, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveJemaatRow
	for rows.Next() {
		var r ListAllActiveJemaatRow
		if err := rows.Scan(&r.ID, &r.NamaLengkap, &r.NamaPanggilan); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}
