// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jemaat.sql

package sqlc

import (
	"context"
)

const countJemaatByChurch = `-- name: CountJemaatByChurch :one
SELECT COUNT(*) FROM jemaat WHERE church_id = ? AND is_active = 1
`

func (q *Queries) CountJemaatByChurch(ctx context.Context, churchID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJemaatByChurch, churchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJemaat = `-- name: CreateJemaat :one
INSERT INTO jemaat (
    church_id, nama_lengkap, nama_panggilan, jenis_kelamin,
    tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email,
    status_pernikahan, tanggal_baptis, tanggal_sidi,
    keluarga_id, catatan
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type CreateJemaatParams struct {
	ChurchID         int64   `db:"church_id" json:"church_id"`
	NamaLengkap      string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    *string `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     *string `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     *string `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      *string `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           *string `db:"alamat" json:"alamat"`
	NomorTelepon     *string `db:"nomor_telepon" json:"nomor_telepon"`
	Email            *string `db:"email" json:"email"`
	StatusPernikahan *string `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    *string `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      *string `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       *int64  `db:"keluarga_id" json:"keluarga_id"`
	Catatan          *string `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, createJemaat,
		arg.ChurchID,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateJemaat = `-- name: DeactivateJemaat :exec
UPDATE jemaat SET is_active = 0, updated_at = datetime('now')
WHERE id = ? AND church_id = ?
`

type DeactivateJemaatParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error {
	_, err := q.db.ExecContext(ctx, deactivateJemaat, arg.ID, arg.ChurchID)
	return err
}

const deleteJemaat = `-- name: DeleteJemaat :exec
DELETE FROM jemaat WHERE id = ? AND church_id = ?
`

type DeleteJemaatParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeleteJemaat(ctx context.Context, arg DeleteJemaatParams) error {
	_, err := q.db.ExecContext(ctx, deleteJemaat, arg.ID, arg.ChurchID)
	return err
}

const getJemaatByID = `-- name: GetJemaatByID :one
SELECT id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE id = ? AND church_id = ?
`

type GetJemaatByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) GetJemaatByID(ctx context.Context, arg GetJemaatByIDParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, getJemaatByID, arg.ID, arg.ChurchID)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJemaatByChurch = `-- name: ListJemaatByChurch :many
SELECT id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE church_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
LIMIT ? OFFSET ?
`

type ListJemaatByChurchParams struct {
	ChurchID int64 `db:"church_id" json:"church_id"`
	Limit    int64 `db:"limit" json:"limit"`
	Offset   int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListJemaatByChurch(ctx context.Context, arg ListJemaatByChurchParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaatByChurch, arg.ChurchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJemaat = `-- name: SearchJemaat :many
SELECT id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE church_id = ? AND is_active = 1
  AND (nama_lengkap LIKE ? OR nama_panggilan LIKE ? OR email LIKE ?)
ORDER BY nama_lengkap ASC
LIMIT ? OFFSET ?
`

type SearchJemaatParams struct {
	ChurchID      int64   `db:"church_id" json:"church_id"`
	NamaLengkap   string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan *string `db:"nama_panggilan" json:"nama_panggilan"`
	Email         *string `db:"email" json:"email"`
	Limit         int64   `db:"limit" json:"limit"`
	Offset        int64   `db:"offset" json:"offset"`
}

func (q *Queries) SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, searchJemaat,
		arg.ChurchID,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.Email,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJemaat = `-- name: UpdateJemaat :one
UPDATE jemaat SET
    nama_lengkap = ?,
    nama_panggilan = ?,
    jenis_kelamin = ?,
    tanggal_lahir = ?,
    tempat_lahir = ?,
    alamat = ?,
    nomor_telepon = ?,
    email = ?,
    status_pernikahan = ?,
    tanggal_baptis = ?,
    tanggal_sidi = ?,
    keluarga_id = ?,
    catatan = ?,
    updated_at = datetime('now')
WHERE id = ? AND church_id = ?
RETURNING id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type UpdateJemaatParams struct {
	NamaLengkap      string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    *string `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     *string `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     *string `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      *string `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           *string `db:"alamat" json:"alamat"`
	NomorTelepon     *string `db:"nomor_telepon" json:"nomor_telepon"`
	Email            *string `db:"email" json:"email"`
	StatusPernikahan *string `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    *string `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      *string `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       *int64  `db:"keluarga_id" json:"keluarga_id"`
	Catatan          *string `db:"catatan" json:"catatan"`
	ID               int64   `db:"id" json:"id"`
	ChurchID         int64   `db:"church_id" json:"church_id"`
}

func (q *Queries) UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, updateJemaat,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
		arg.ID,
		arg.ChurchID,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
