// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jemaat.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countJemaat = `-- name: CountJemaat :one
SELECT COUNT(*) FROM jemaat WHERE user_id = ? AND is_active = 1
`

func (q *Queries) CountJemaat(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJemaat, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchJemaat = `-- name: CountSearchJemaat :one
SELECT COUNT(*) FROM jemaat
WHERE user_id = ? AND is_active = 1 AND nama_lengkap LIKE ?
`

type CountSearchJemaatParams struct {
	UserID      int64  `json:"user_id"`
	NamaLengkap string `json:"nama_lengkap"`
}

func (q *Queries) CountSearchJemaat(ctx context.Context, arg CountSearchJemaatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchJemaat, arg.UserID, arg.NamaLengkap)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJemaat = `-- name: CreateJemaat :one
INSERT INTO jemaat (
    user_id, nama_lengkap, nama_panggilan, jenis_kelamin,
    tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email,
    status_pernikahan, tanggal_baptis, tanggal_sidi,
    keluarga_id, catatan
) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type CreateJemaatParams struct {
	UserID           int64          `json:"user_id"`
	NamaLengkap      string         `json:"nama_lengkap"`
	NamaPanggilan    sql.NullString `json:"nama_panggilan"`
	JenisKelamin     sql.NullString `json:"jenis_kelamin"`
	TanggalLahir     sql.NullString `json:"tanggal_lahir"`
	TempatLahir      sql.NullString `json:"tempat_lahir"`
	Alamat           sql.NullString `json:"alamat"`
	NomorTelepon     sql.NullString `json:"nomor_telepon"`
	Email            sql.NullString `json:"email"`
	StatusPernikahan sql.NullString `json:"status_pernikahan"`
	TanggalBaptis    sql.NullString `json:"tanggal_baptis"`
	TanggalSidi      sql.NullString `json:"tanggal_sidi"`
	KeluargaID       sql.NullInt64  `json:"keluarga_id"`
	Catatan          sql.NullString `json:"catatan"`
}

func (q *Queries) CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, createJemaat,
		arg.UserID,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateJemaat = `-- name: DeactivateJemaat :exec
UPDATE jemaat SET is_active=0,
    updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id=? AND user_id=?
`

type DeactivateJemaatParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error {
	_, err := q.db.ExecContext(ctx, deactivateJemaat, arg.ID, arg.UserID)
	return err
}

const getJemaat = `-- name: GetJemaat :one
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat WHERE id = ? AND user_id = ?
`

type GetJemaatParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetJemaat(ctx context.Context, arg GetJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, getJemaat, arg.ID, arg.UserID)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveJemaatNames = `-- name: ListActiveJemaatNames :many
SELECT id, nama_lengkap FROM jemaat
WHERE user_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
`

type ListActiveJemaatNamesRow struct {
	ID          int64  `json:"id"`
	NamaLengkap string `json:"nama_lengkap"`
}

func (q *Queries) ListActiveJemaatNames(ctx context.Context, userID int64) ([]ListActiveJemaatNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJemaatNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveJemaatNamesRow{}
	for rows.Next() {
		var i ListActiveJemaatNamesRow
		if err := rows.Scan(&i.ID, &i.NamaLengkap); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJemaat = `-- name: ListJemaat :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
LIMIT ? OFFSET ?
`

type ListJemaatParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListJemaat(ctx context.Context, arg ListJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaat, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJemaatByKeluarga = `-- name: ListJemaatByKeluarga :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ? AND keluarga_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
`

type ListJemaatByKeluargaParams struct {
	UserID     int64         `json:"user_id"`
	KeluargaID sql.NullInt64 `json:"keluarga_id"`
}

func (q *Queries) ListJemaatByKeluarga(ctx context.Context, arg ListJemaatByKeluargaParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaatByKeluarga, arg.UserID, arg.KeluargaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJemaat = `-- name: SearchJemaat :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ? AND is_active = 1 AND nama_lengkap LIKE ?
ORDER BY nama_lengkap ASC
LIMIT ? OFFSET ?
`

type SearchJemaatParams struct {
	UserID      int64  `json:"user_id"`
	NamaLengkap string `json:"nama_lengkap"`
	Limit       int64  `json:"limit"`
	Offset      int64  `json:"offset"`
}

func (q *Queries) SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, searchJemaat,
		arg.UserID,
		arg.NamaLengkap,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJemaat = `-- name: UpdateJemaat :one
UPDATE jemaat SET
    nama_lengkap=?, nama_panggilan=?, jenis_kelamin=?,
    tanggal_lahir=?, tempat_lahir=?, alamat=?, nomor_telepon=?, email=?,
    status_pernikahan=?, tanggal_baptis=?, tanggal_sidi=?, keluarga_id=?, catatan=?,
    updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id=? AND user_id=? RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type UpdateJemaatParams struct {
	NamaLengkap      string         `json:"nama_lengkap"`
	NamaPanggilan    sql.NullString `json:"nama_panggilan"`
	JenisKelamin     sql.NullString `json:"jenis_kelamin"`
	TanggalLahir     sql.NullString `json:"tanggal_lahir"`
	TempatLahir      sql.NullString `json:"tempat_lahir"`
	Alamat           sql.NullString `json:"alamat"`
	NomorTelepon     sql.NullString `json:"nomor_telepon"`
	Email            sql.NullString `json:"email"`
	StatusPernikahan sql.NullString `json:"status_pernikahan"`
	TanggalBaptis    sql.NullString `json:"tanggal_baptis"`
	TanggalSidi      sql.NullString `json:"tanggal_sidi"`
	KeluargaID       sql.NullInt64  `json:"keluarga_id"`
	Catatan          sql.NullString `json:"catatan"`
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
}

func (q *Queries) UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, updateJemaat,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
