// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const getKebaktian = `SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE id = ? AND user_id = ?`

type GetKebaktianParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetKebaktian(ctx context.Context, arg GetKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, getKebaktian, arg.ID, arg.UserID)
	var k Kebaktian
	err := row.Scan(&k.ID, &k.UserID, &k.Nama, &k.WaktuMulai, &k.Lokasi, &k.Tema, &k.Pengkhotbah, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const listKebaktian = `SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE user_id = ? ORDER BY waktu_mulai DESC LIMIT ? OFFSET ?`

type ListKebaktianParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListKebaktian(ctx context.Context, arg ListKebaktianParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktian, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanKebaktianRows(rows)
}

const listKebaktianRange = `SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE user_id = ? AND waktu_mulai >= ? AND waktu_mulai <= ? ORDER BY waktu_mulai ASC`

type ListKebaktianRangeParams struct {
	UserID string
	From   string
	To     string
}

func (q *Queries) ListKebaktianRange(ctx context.Context, userID int64, from, to string) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktianRange, userID, from, to)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return scanKebaktianRows(rows)
}

func scanKebaktianRows(rows *sql.Rows) ([]Kebaktian, error) {
	var items []Kebaktian
	for rows.Next() {
		var k Kebaktian
		if err := rows.Scan(&k.ID, &k.UserID, &k.Nama, &k.WaktuMulai, &k.Lokasi, &k.Tema, &k.Pengkhotbah, &k.Catatan, &k.CreatedAt, &k.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, k)
	}
	return items, rows.Err()
}

const countKebaktian = `SELECT COUNT(*) FROM kebaktian WHERE user_id = ?`

func (q *Queries) CountKebaktian(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKebaktian, userID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createKebaktian = `INSERT INTO kebaktian (user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at`

type CreateKebaktianParams struct {
	UserID      int64
	Nama        string
	WaktuMulai  string
	Lokasi      sql.NullString
	Tema        sql.NullString
	Pengkhotbah sql.NullString
	Catatan     sql.NullString
}

func (q *Queries) CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, createKebaktian, arg.UserID, arg.Nama, arg.WaktuMulai, arg.Lokasi, arg.Tema, arg.Pengkhotbah, arg.Catatan)
	var k Kebaktian
	err := row.Scan(&k.ID, &k.UserID, &k.Nama, &k.WaktuMulai, &k.Lokasi, &k.Tema, &k.Pengkhotbah, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const updateKebaktian = `UPDATE kebaktian SET nama=?, waktu_mulai=?, lokasi=?, tema=?, pengkhotbah=?, catatan=?, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND user_id=? RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at`

type UpdateKebaktianParams struct {
	Nama        string
	WaktuMulai  string
	Lokasi      sql.NullString
	Tema        sql.NullString
	Pengkhotbah sql.NullString
	Catatan     sql.NullString
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, updateKebaktian, arg.Nama, arg.WaktuMulai, arg.Lokasi, arg.Tema, arg.Pengkhotbah, arg.Catatan, arg.ID, arg.UserID)
	var k Kebaktian
	err := row.Scan(&k.ID, &k.UserID, &k.Nama, &k.WaktuMulai, &k.Lokasi, &k.Tema, &k.Pengkhotbah, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const deleteKebaktian = `DELETE FROM kebaktian WHERE id = ? AND user_id = ?`

type DeleteKebaktianParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteKebaktian, arg.ID, arg.UserID)
	return err
}
