// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: kebaktian.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createKebaktian = `-- name: CreateKebaktian :one
INSERT INTO kebaktian (user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type CreateKebaktianParams struct {
	UserID      int64          `json:"user_id"`
	Nama        string         `json:"nama"`
	WaktuMulai  string         `json:"waktu_mulai"`
	Lokasi      sql.NullString `json:"lokasi"`
	Tema        sql.NullString `json:"tema"`
	Pengkhotbah sql.NullString `json:"pengkhotbah"`
	Catatan     sql.NullString `json:"catatan"`
}

func (q *Queries) CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, createKebaktian,
		arg.UserID,
		arg.Nama,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKebaktian = `-- name: DeleteKebaktian :exec
DELETE FROM kebaktian WHERE id = ? AND user_id = ?
`

type DeleteKebaktianParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteKebaktian, arg.ID, arg.UserID)
	return err
}

const getKebaktian = `-- name: GetKebaktian :one
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE id = ? AND user_id = ?
`

type GetKebaktianParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetKebaktian(ctx context.Context, arg GetKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, getKebaktian, arg.ID, arg.UserID)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKebaktian = `-- name: ListKebaktian :many
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian
WHERE user_id = ?
ORDER BY waktu_mulai DESC
LIMIT ? OFFSET ?
`

type ListKebaktianParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListKebaktian(ctx context.Context, arg ListKebaktianParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktian, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kebaktian{}
	for rows.Next() {
		var i Kebaktian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.WaktuMulai,
			&i.Lokasi,
			&i.Tema,
			&i.Pengkhotbah,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKebaktianRange = `-- name: ListKebaktianRange :many
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian
WHERE user_id = ? AND waktu_mulai >= ? AND waktu_mulai <= ?
ORDER BY waktu_mulai ASC
`

type ListKebaktianRangeParams struct {
	UserID       int64  `json:"user_id"`
	WaktuMulai   string `json:"waktu_mulai"`
	WaktuMulai_2 string `json:"waktu_mulai_2"`
}

func (q *Queries) ListKebaktianRange(ctx context.Context, arg ListKebaktianRangeParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktianRange, arg.UserID, arg.WaktuMulai, arg.WaktuMulai_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kebaktian{}
	for rows.Next() {
		var i Kebaktian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.WaktuMulai,
			&i.Lokasi,
			&i.Tema,
			&i.Pengkhotbah,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKebaktian = `-- name: UpdateKebaktian :one
UPDATE kebaktian SET
    nama = ?, waktu_mulai = ?, lokasi = ?, tema = ?, pengkhotbah = ?, catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type UpdateKebaktianParams struct {
	Nama        string         `json:"nama"`
	WaktuMulai  string         `json:"waktu_mulai"`
	Lokasi      sql.NullString `json:"lokasi"`
	Tema        sql.NullString `json:"tema"`
	Pengkhotbah sql.NullString `json:"pengkhotbah"`
	Catatan     sql.NullString `json:"catatan"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, updateKebaktian,
		arg.Nama,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
