// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keluarga.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createKeluarga = `-- name: CreateKeluarga :one
INSERT INTO keluarga (user_id, nama_keluarga, alamat, catatan)
VALUES (?, ?, ?, ?) RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type CreateKeluargaParams struct {
	UserID       int64          `json:"user_id"`
	NamaKeluarga string         `json:"nama_keluarga"`
	Alamat       sql.NullString `json:"alamat"`
	Catatan      sql.NullString `json:"catatan"`
}

func (q *Queries) CreateKeluarga(ctx context.Context, arg CreateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, createKeluarga,
		arg.UserID,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKeluarga = `-- name: DeleteKeluarga :exec
DELETE FROM keluarga WHERE id = ? AND user_id = ?
`

type DeleteKeluargaParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteKeluarga(ctx context.Context, arg DeleteKeluargaParams) error {
	_, err := q.db.ExecContext(ctx, deleteKeluarga, arg.ID, arg.UserID)
	return err
}

const getKeluarga = `-- name: GetKeluarga :one
SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga WHERE id = ? AND user_id = ?
`

type GetKeluargaParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetKeluarga(ctx context.Context, arg GetKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, getKeluarga, arg.ID, arg.UserID)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKeluarga = `-- name: ListKeluarga :many
SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga
WHERE user_id = ?
ORDER BY nama_keluarga ASC
`

func (q *Queries) ListKeluarga(ctx context.Context, userID int64) ([]Keluarga, error) {
	rows, err := q.db.QueryContext(ctx, listKeluarga, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Keluarga{}
	for rows.Next() {
		var i Keluarga
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaKeluarga,
			&i.Alamat,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeluargaOptions = `-- name: ListKeluargaOptions :many
SELECT id, nama_keluarga FROM keluarga
WHERE user_id = ?
ORDER BY nama_keluarga ASC
`

type ListKeluargaOptionsRow struct {
	ID           int64  `json:"id"`
	NamaKeluarga string `json:"nama_keluarga"`
}

func (q *Queries) ListKeluargaOptions(ctx context.Context, userID int64) ([]ListKeluargaOptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listKeluargaOptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeluargaOptionsRow{}
	for rows.Next() {
		var i ListKeluargaOptionsRow
		if err := rows.Scan(&i.ID, &i.NamaKeluarga); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeluarga = `-- name: UpdateKeluarga :one
UPDATE keluarga SET
    nama_keluarga = ?, alamat = ?, catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type UpdateKeluargaParams struct {
	NamaKeluarga string         `json:"nama_keluarga"`
	Alamat       sql.NullString `json:"alamat"`
	Catatan      sql.NullString `json:"catatan"`
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
}

func (q *Queries) UpdateKeluarga(ctx context.Context, arg UpdateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, updateKeluarga,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
