// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keluarga.sql

package sqlc

import (
	"context"
)

const countKeluargaByChurch = `-- name: CountKeluargaByChurch :one
SELECT COUNT(*) FROM keluarga WHERE church_id = ?
`

func (q *Queries) CountKeluargaByChurch(ctx context.Context, churchID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKeluargaByChurch, churchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createKeluarga = `-- name: CreateKeluarga :one
INSERT INTO keluarga (church_id, nama_keluarga, alamat, catatan)
VALUES (?, ?, ?, ?)
RETURNING id, church_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type CreateKeluargaParams struct {
	ChurchID     int64   `db:"church_id" json:"church_id"`
	NamaKeluarga string  `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       *string `db:"alamat" json:"alamat"`
	Catatan      *string `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateKeluarga(ctx context.Context, arg CreateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, createKeluarga,
		arg.ChurchID,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKeluarga = `-- name: DeleteKeluarga :exec
DELETE FROM keluarga WHERE id = ? AND church_id = ?
`

type DeleteKeluargaParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeleteKeluarga(ctx context.Context, arg DeleteKeluargaParams) error {
	_, err := q.db.ExecContext(ctx, deleteKeluarga, arg.ID, arg.ChurchID)
	return err
}

const getKeluargaByID = `-- name: GetKeluargaByID :one
SELECT id, church_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga WHERE id = ? AND church_id = ?
`

type GetKeluargaByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) GetKeluargaByID(ctx context.Context, arg GetKeluargaByIDParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, getKeluargaByID, arg.ID, arg.ChurchID)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJemaatByKeluarga = `-- name: ListJemaatByKeluarga :many
SELECT id, church_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE keluarga_id = ? AND church_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
`

type ListJemaatByKeluargaParams struct {
	KeluargaID *int64 `db:"keluarga_id" json:"keluarga_id"`
	ChurchID   int64  `db:"church_id" json:"church_id"`
}

func (q *Queries) ListJemaatByKeluarga(ctx context.Context, arg ListJemaatByKeluargaParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaatByKeluarga, arg.KeluargaID, arg.ChurchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeluargaByChurch = `-- name: ListKeluargaByChurch :many
SELECT id, church_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga
WHERE church_id = ?
ORDER BY nama_keluarga ASC
LIMIT ? OFFSET ?
`

type ListKeluargaByChurchParams struct {
	ChurchID int64 `db:"church_id" json:"church_id"`
	Limit    int64 `db:"limit" json:"limit"`
	Offset   int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListKeluargaByChurch(ctx context.Context, arg ListKeluargaByChurchParams) ([]Keluarga, error) {
	rows, err := q.db.QueryContext(ctx, listKeluargaByChurch, arg.ChurchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Keluarga{}
	for rows.Next() {
		var i Keluarga
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.NamaKeluarga,
			&i.Alamat,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKeluarga = `-- name: SearchKeluarga :many
SELECT id, church_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga
WHERE church_id = ?
  AND (nama_keluarga LIKE ? OR alamat LIKE ?)
ORDER BY nama_keluarga ASC
LIMIT ? OFFSET ?
`

type SearchKeluargaParams struct {
	ChurchID     int64   `db:"church_id" json:"church_id"`
	NamaKeluarga string  `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       *string `db:"alamat" json:"alamat"`
	Limit        int64   `db:"limit" json:"limit"`
	Offset       int64   `db:"offset" json:"offset"`
}

func (q *Queries) SearchKeluarga(ctx context.Context, arg SearchKeluargaParams) ([]Keluarga, error) {
	rows, err := q.db.QueryContext(ctx, searchKeluarga,
		arg.ChurchID,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Keluarga{}
	for rows.Next() {
		var i Keluarga
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.NamaKeluarga,
			&i.Alamat,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeluarga = `-- name: UpdateKeluarga :one
UPDATE keluarga SET
    nama_keluarga = ?,
    alamat = ?,
    catatan = ?,
    updated_at = datetime('now')
WHERE id = ? AND church_id = ?
RETURNING id, church_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type UpdateKeluargaParams struct {
	NamaKeluarga string  `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       *string `db:"alamat" json:"alamat"`
	Catatan      *string `db:"catatan" json:"catatan"`
	ID           int64   `db:"id" json:"id"`
	ChurchID     int64   `db:"church_id" json:"church_id"`
}

func (q *Queries) UpdateKeluarga(ctx context.Context, arg UpdateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, updateKeluarga,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
		arg.ID,
		arg.ChurchID,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
