// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const getKeluarga = `SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga WHERE id = ? AND user_id = ?`

type GetKeluargaParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetKeluarga(ctx context.Context, arg GetKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, getKeluarga, arg.ID, arg.UserID)
	var k Keluarga
	err := row.Scan(&k.ID, &k.UserID, &k.NamaKeluarga, &k.Alamat, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const listKeluarga = `SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga WHERE user_id = ? ORDER BY nama_keluarga ASC LIMIT ? OFFSET ?`

type ListKeluargaParams struct {
	UserID int64
	Limit  int64
	Offset int64
}

func (q *Queries) ListKeluarga(ctx context.Context, arg ListKeluargaParams) ([]Keluarga, error) {
	rows, err := q.db.QueryContext(ctx, listKeluarga, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Keluarga
	for rows.Next() {
		var k Keluarga
		if err := rows.Scan(&k.ID, &k.UserID, &k.NamaKeluarga, &k.Alamat, &k.Catatan, &k.CreatedAt, &k.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, k)
	}
	return items, rows.Err()
}

const countKeluarga = `SELECT COUNT(*) FROM keluarga WHERE user_id = ?`

func (q *Queries) CountKeluarga(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKeluarga, userID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const listAllKeluarga = `SELECT id, nama_keluarga FROM keluarga WHERE user_id = ? ORDER BY nama_keluarga ASC`

type ListAllKeluargaRow struct {
	ID           int64  `json:"id"`
	NamaKeluarga string `json:"nama_keluarga"`
}

func (q *Queries) ListAllKeluarga(ctx context.Context, userID int64) ([]ListAllKeluargaRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllKeluarga, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllKeluargaRow
	for rows.Next() {
		var r ListAllKeluargaRow
		if err := rows.Scan(&r.ID, &r.NamaKeluarga); err != nil {
			return nil, err
		}
		items = append(items, r)
	}
	return items, rows.Err()
}

const createKeluarga = `INSERT INTO keluarga (user_id, nama_keluarga, alamat, catatan) VALUES (?, ?, ?, ?) RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at`

type CreateKeluargaParams struct {
	UserID       int64
	NamaKeluarga string
	Alamat       sql.NullString
	Catatan      sql.NullString
}

func (q *Queries) CreateKeluarga(ctx context.Context, arg CreateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, createKeluarga, arg.UserID, arg.NamaKeluarga, arg.Alamat, arg.Catatan)
	var k Keluarga
	err := row.Scan(&k.ID, &k.UserID, &k.NamaKeluarga, &k.Alamat, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const updateKeluarga = `UPDATE keluarga SET nama_keluarga = ?, alamat = ?, catatan = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id = ? AND user_id = ? RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at`

type UpdateKeluargaParams struct {
	NamaKeluarga string
	Alamat       sql.NullString
	Catatan      sql.NullString
	ID           int64
	UserID       int64
}

func (q *Queries) UpdateKeluarga(ctx context.Context, arg UpdateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, updateKeluarga, arg.NamaKeluarga, arg.Alamat, arg.Catatan, arg.ID, arg.UserID)
	var k Keluarga
	err := row.Scan(&k.ID, &k.UserID, &k.NamaKeluarga, &k.Alamat, &k.Catatan, &k.CreatedAt, &k.UpdatedAt)
	return k, err
}

const deleteKeluarga = `DELETE FROM keluarga WHERE id = ? AND user_id = ?`

type DeleteKeluargaParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteKeluarga(ctx context.Context, arg DeleteKeluargaParams) error {
	_, err := q.db.ExecContext(ctx, deleteKeluarga, arg.ID, arg.UserID)
	return err
}
