// Code generated by sqlc. DO NOT EDIT.

package sqlc

import "database/sql"

type User struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	DisplayName  string         `json:"display_name"`
	ChurchName   string         `json:"church_name"`
	Timezone     string         `json:"timezone"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Session struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type Keluarga struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	NamaKeluarga string         `json:"nama_keluarga"`
	Alamat       sql.NullString `json:"alamat"`
	Catatan      sql.NullString `json:"catatan"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type Jemaat struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	NamaLengkap      string         `json:"nama_lengkap"`
	NamaPanggilan    sql.NullString `json:"nama_panggilan"`
	JenisKelamin     sql.NullString `json:"jenis_kelamin"`
	TanggalLahir     sql.NullString `json:"tanggal_lahir"`
	TempatLahir      sql.NullString `json:"tempat_lahir"`
	Alamat           sql.NullString `json:"alamat"`
	NomorTelepon     sql.NullString `json:"nomor_telepon"`
	Email            sql.NullString `json:"email"`
	StatusPernikahan sql.NullString `json:"status_pernikahan"`
	TanggalBaptis    sql.NullString `json:"tanggal_baptis"`
	TanggalSidi      sql.NullString `json:"tanggal_sidi"`
	KeluargaID       sql.NullInt64  `json:"keluarga_id"`
	Catatan          sql.NullString `json:"catatan"`
	IsActive         int64          `json:"is_active"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type ServiceType struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Nama      string         `json:"nama"`
	Deskripsi sql.NullString `json:"deskripsi"`
	Urutan    int64          `json:"urutan"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Pelayan struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	JemaatID  int64          `json:"jemaat_id"`
	Catatan   sql.NullString `json:"catatan"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type PelayanRow struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	JemaatID    int64          `json:"jemaat_id"`
	Catatan     sql.NullString `json:"catatan"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	JemaatNama  string         `json:"jemaat_nama"`
}

type Kebaktian struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	Nama        string         `json:"nama"`
	WaktuMulai  string         `json:"waktu_mulai"`
	Lokasi      sql.NullString `json:"lokasi"`
	Tema        sql.NullString `json:"tema"`
	Pengkhotbah sql.NullString `json:"pengkhotbah"`
	Catatan     sql.NullString `json:"catatan"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type JadwalPelayanan struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	KebaktianID   int64          `json:"kebaktian_id"`
	ServiceTypeID int64          `json:"service_type_id"`
	PelayanID     sql.NullInt64  `json:"pelayan_id"`
	Catatan       sql.NullString `json:"catatan"`
	Confirmed     int64          `json:"confirmed"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type JadwalRow struct {
	ID                  int64          `json:"id"`
	UserID              int64          `json:"user_id"`
	KebaktianID         int64          `json:"kebaktian_id"`
	ServiceTypeID       int64          `json:"service_type_id"`
	PelayanID           sql.NullInt64  `json:"pelayan_id"`
	Catatan             sql.NullString `json:"catatan"`
	Confirmed           int64          `json:"confirmed"`
	CreatedAt           string         `json:"created_at"`
	UpdatedAt           string         `json:"updated_at"`
	ServiceTypeNama     string         `json:"service_type_nama"`
	ServiceTypeUrutan   int64          `json:"service_type_urutan"`
	PelayanNama         sql.NullString `json:"pelayan_nama"`
}
