// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type AuditLog struct {
	ID          int64   `db:"id" json:"id"`
	ChurchID    int64   `db:"church_id" json:"church_id"`
	UserID      *int64  `db:"user_id" json:"user_id"`
	Action      string  `db:"action" json:"action"`
	EntityType  string  `db:"entity_type" json:"entity_type"`
	EntityID    *int64  `db:"entity_id" json:"entity_id"`
	PayloadJson *string `db:"payload_json" json:"payload_json"`
	CreatedAt   string  `db:"created_at" json:"created_at"`
}

type Church struct {
	ID        int64  `db:"id" json:"id"`
	Name      string `db:"name" json:"name"`
	Slug      string `db:"slug" json:"slug"`
	Timezone  string `db:"timezone" json:"timezone"`
	CreatedAt string `db:"created_at" json:"created_at"`
	UpdatedAt string `db:"updated_at" json:"updated_at"`
}

type JadwalPelayanan struct {
	ID            int64   `db:"id" json:"id"`
	ChurchID      int64   `db:"church_id" json:"church_id"`
	KebaktianID   int64   `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID int64   `db:"service_type_id" json:"service_type_id"`
	PelayanID     *int64  `db:"pelayan_id" json:"pelayan_id"`
	Catatan       *string `db:"catatan" json:"catatan"`
	Status        string  `db:"status" json:"status"`
	CreatedAt     string  `db:"created_at" json:"created_at"`
	UpdatedAt     string  `db:"updated_at" json:"updated_at"`
}

type Jemaat struct {
	ID               int64   `db:"id" json:"id"`
	ChurchID         int64   `db:"church_id" json:"church_id"`
	NamaLengkap      string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    *string `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     *string `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     *string `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      *string `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           *string `db:"alamat" json:"alamat"`
	NomorTelepon     *string `db:"nomor_telepon" json:"nomor_telepon"`
	Email            *string `db:"email" json:"email"`
	StatusPernikahan *string `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    *string `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      *string `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       *int64  `db:"keluarga_id" json:"keluarga_id"`
	Catatan          *string `db:"catatan" json:"catatan"`
	IsActive         int64   `db:"is_active" json:"is_active"`
	CreatedAt        string  `db:"created_at" json:"created_at"`
	UpdatedAt        string  `db:"updated_at" json:"updated_at"`
}

type Kebaktian struct {
	ID          int64   `db:"id" json:"id"`
	ChurchID    int64   `db:"church_id" json:"church_id"`
	Nama        string  `db:"nama" json:"nama"`
	Tanggal     string  `db:"tanggal" json:"tanggal"`
	WaktuMulai  string  `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      *string `db:"lokasi" json:"lokasi"`
	Tema        *string `db:"tema" json:"tema"`
	Pengkhotbah *string `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     *string `db:"catatan" json:"catatan"`
	CreatedAt   string  `db:"created_at" json:"created_at"`
	UpdatedAt   string  `db:"updated_at" json:"updated_at"`
}

type Keluarga struct {
	ID           int64   `db:"id" json:"id"`
	ChurchID     int64   `db:"church_id" json:"church_id"`
	NamaKeluarga string  `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       *string `db:"alamat" json:"alamat"`
	Catatan      *string `db:"catatan" json:"catatan"`
	CreatedAt    string  `db:"created_at" json:"created_at"`
	UpdatedAt    string  `db:"updated_at" json:"updated_at"`
}

type Pelayan struct {
	ID        int64   `db:"id" json:"id"`
	ChurchID  int64   `db:"church_id" json:"church_id"`
	JemaatID  int64   `db:"jemaat_id" json:"jemaat_id"`
	Catatan   *string `db:"catatan" json:"catatan"`
	IsActive  int64   `db:"is_active" json:"is_active"`
	CreatedAt string  `db:"created_at" json:"created_at"`
	UpdatedAt string  `db:"updated_at" json:"updated_at"`
}

type PelayanServiceType struct {
	PelayanID     int64   `db:"pelayan_id" json:"pelayan_id"`
	ServiceTypeID int64   `db:"service_type_id" json:"service_type_id"`
	SkillLevel    *string `db:"skill_level" json:"skill_level"`
	CreatedAt     string  `db:"created_at" json:"created_at"`
}

type ServiceType struct {
	ID        int64   `db:"id" json:"id"`
	ChurchID  int64   `db:"church_id" json:"church_id"`
	Nama      string  `db:"nama" json:"nama"`
	Deskripsi *string `db:"deskripsi" json:"deskripsi"`
	Warna     *string `db:"warna" json:"warna"`
	Urutan    int64   `db:"urutan" json:"urutan"`
	IsActive  int64   `db:"is_active" json:"is_active"`
	CreatedAt string  `db:"created_at" json:"created_at"`
	UpdatedAt string  `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int64   `db:"id" json:"id"`
	ChurchID     int64   `db:"church_id" json:"church_id"`
	Email        string  `db:"email" json:"email"`
	PasswordHash string  `db:"password_hash" json:"password_hash"`
	DisplayName  string  `db:"display_name" json:"display_name"`
	Role         string  `db:"role" json:"role"`
	IsActive     int64   `db:"is_active" json:"is_active"`
	LastLoginAt  *string `db:"last_login_at" json:"last_login_at"`
	CreatedAt    string  `db:"created_at" json:"created_at"`
	UpdatedAt    string  `db:"updated_at" json:"updated_at"`
}
