// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	null "gopkg.in/guregu/null.v4"
)

type JadwalPelayanan struct {
	ID            int64       `db:"id" json:"id"`
	UserID        int64       `db:"user_id" json:"user_id"`
	KebaktianID   int64       `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID int64       `db:"service_type_id" json:"service_type_id"`
	PelayanID     null.Int    `db:"pelayan_id" json:"pelayan_id"`
	Catatan       null.String `db:"catatan" json:"catatan"`
	Confirmed     int64       `db:"confirmed" json:"confirmed"`
	CreatedAt     string      `db:"created_at" json:"created_at"`
	UpdatedAt     string      `db:"updated_at" json:"updated_at"`
}

type Jemaat struct {
	ID               int64       `db:"id" json:"id"`
	UserID           int64       `db:"user_id" json:"user_id"`
	NamaLengkap      string      `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    null.String `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     null.String `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     null.String `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      null.String `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           null.String `db:"alamat" json:"alamat"`
	NomorTelepon     null.String `db:"nomor_telepon" json:"nomor_telepon"`
	Email            null.String `db:"email" json:"email"`
	StatusPernikahan null.String `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    null.String `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      null.String `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       null.Int    `db:"keluarga_id" json:"keluarga_id"`
	Catatan          null.String `db:"catatan" json:"catatan"`
	IsActive         int64       `db:"is_active" json:"is_active"`
	CreatedAt        string      `db:"created_at" json:"created_at"`
	UpdatedAt        string      `db:"updated_at" json:"updated_at"`
}

type Kebaktian struct {
	ID          int64       `db:"id" json:"id"`
	UserID      int64       `db:"user_id" json:"user_id"`
	Nama        string      `db:"nama" json:"nama"`
	WaktuMulai  string      `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      null.String `db:"lokasi" json:"lokasi"`
	Tema        null.String `db:"tema" json:"tema"`
	Pengkhotbah null.String `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     null.String `db:"catatan" json:"catatan"`
	CreatedAt   string      `db:"created_at" json:"created_at"`
	UpdatedAt   string      `db:"updated_at" json:"updated_at"`
}

type Keluarga struct {
	ID           int64       `db:"id" json:"id"`
	UserID       int64       `db:"user_id" json:"user_id"`
	NamaKeluarga string      `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       null.String `db:"alamat" json:"alamat"`
	Catatan      null.String `db:"catatan" json:"catatan"`
	CreatedAt    string      `db:"created_at" json:"created_at"`
	UpdatedAt    string      `db:"updated_at" json:"updated_at"`
}

type Pelayan struct {
	ID        int64       `db:"id" json:"id"`
	UserID    int64       `db:"user_id" json:"user_id"`
	JemaatID  int64       `db:"jemaat_id" json:"jemaat_id"`
	Catatan   null.String `db:"catatan" json:"catatan"`
	CreatedAt string      `db:"created_at" json:"created_at"`
	UpdatedAt string      `db:"updated_at" json:"updated_at"`
}

type PelayanServiceType struct {
	PelayanID     int64  `db:"pelayan_id" json:"pelayan_id"`
	ServiceTypeID int64  `db:"service_type_id" json:"service_type_id"`
	CreatedAt     string `db:"created_at" json:"created_at"`
}

type ServiceType struct {
	ID        int64       `db:"id" json:"id"`
	UserID    int64       `db:"user_id" json:"user_id"`
	Nama      string      `db:"nama" json:"nama"`
	Deskripsi null.String `db:"deskripsi" json:"deskripsi"`
	Urutan    int64       `db:"urutan" json:"urutan"`
	CreatedAt string      `db:"created_at" json:"created_at"`
	UpdatedAt string      `db:"updated_at" json:"updated_at"`
}

type Session struct {
	Token     string `db:"token" json:"token"`
	UserID    int64  `db:"user_id" json:"user_id"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
	CreatedAt string `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64  `db:"id" json:"id"`
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	DisplayName  string `db:"display_name" json:"display_name"`
	ChurchName   string `db:"church_name" json:"church_name"`
	Timezone     string `db:"timezone" json:"timezone"`
	CreatedAt    string `db:"created_at" json:"created_at"`
	UpdatedAt    string `db:"updated_at" json:"updated_at"`
}
