// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pelayan.sql

package sqlc

import (
	"context"
)

const addPelayanServiceType = `-- name: AddPelayanServiceType :exec
INSERT INTO pelayan_service_types (pelayan_id, service_type_id)
VALUES (?, ?)
`

type AddPelayanServiceTypeParams struct {
	PelayanID     int64 `db:"pelayan_id" json:"pelayan_id"`
	ServiceTypeID int64 `db:"service_type_id" json:"service_type_id"`
}

func (q *Queries) AddPelayanServiceType(ctx context.Context, arg AddPelayanServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, addPelayanServiceType, arg.PelayanID, arg.ServiceTypeID)
	return err
}

const clearPelayanServiceTypes = `-- name: ClearPelayanServiceTypes :exec
DELETE FROM pelayan_service_types WHERE pelayan_id = ?
`

func (q *Queries) ClearPelayanServiceTypes(ctx context.Context, pelayanID int64) error {
	_, err := q.db.ExecContext(ctx, clearPelayanServiceTypes, pelayanID)
	return err
}

const countPelayanByChurch = `-- name: CountPelayanByChurch :one
SELECT COUNT(*) FROM pelayan WHERE church_id = ? AND is_active = 1
`

func (q *Queries) CountPelayanByChurch(ctx context.Context, churchID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPelayanByChurch, churchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPelayan = `-- name: CreatePelayan :one
INSERT INTO pelayan (church_id, jemaat_id, catatan)
VALUES (?, ?, ?)
RETURNING id, church_id, jemaat_id, catatan, is_active, created_at, updated_at
`

type CreatePelayanParams struct {
	ChurchID int64   `db:"church_id" json:"church_id"`
	JemaatID int64   `db:"jemaat_id" json:"jemaat_id"`
	Catatan  *string `db:"catatan" json:"catatan"`
}

func (q *Queries) CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, createPelayan, arg.ChurchID, arg.JemaatID, arg.Catatan)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.JemaatID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePelayan = `-- name: DeletePelayan :exec
DELETE FROM pelayan WHERE id = ? AND church_id = ?
`

type DeletePelayanParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeletePelayan(ctx context.Context, arg DeletePelayanParams) error {
	_, err := q.db.ExecContext(ctx, deletePelayan, arg.ID, arg.ChurchID)
	return err
}

const getPelayanByID = `-- name: GetPelayanByID :one
SELECT p.id, p.church_id, p.jemaat_id, p.catatan, p.is_active, p.created_at, p.updated_at, j.nama_lengkap, j.nama_panggilan
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id
WHERE p.id = ? AND p.church_id = ?
`

type GetPelayanByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

type GetPelayanByIDRow struct {
	ID            int64   `db:"id" json:"id"`
	ChurchID      int64   `db:"church_id" json:"church_id"`
	JemaatID      int64   `db:"jemaat_id" json:"jemaat_id"`
	Catatan       *string `db:"catatan" json:"catatan"`
	IsActive      int64   `db:"is_active" json:"is_active"`
	CreatedAt     string  `db:"created_at" json:"created_at"`
	UpdatedAt     string  `db:"updated_at" json:"updated_at"`
	NamaLengkap   string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan *string `db:"nama_panggilan" json:"nama_panggilan"`
}

func (q *Queries) GetPelayanByID(ctx context.Context, arg GetPelayanByIDParams) (GetPelayanByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPelayanByID, arg.ID, arg.ChurchID)
	var i GetPelayanByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.JemaatID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NamaLengkap,
		&i.NamaPanggilan,
	)
	return i, err
}

const getPelayanByJemaatID = `-- name: GetPelayanByJemaatID :one
SELECT id, church_id, jemaat_id, catatan, is_active, created_at, updated_at FROM pelayan
WHERE jemaat_id = ? AND church_id = ?
`

type GetPelayanByJemaatIDParams struct {
	JemaatID int64 `db:"jemaat_id" json:"jemaat_id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) GetPelayanByJemaatID(ctx context.Context, arg GetPelayanByJemaatIDParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, getPelayanByJemaatID, arg.JemaatID, arg.ChurchID)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.JemaatID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceTypesForPelayan = `-- name: GetServiceTypesForPelayan :many
SELECT st.id, st.church_id, st.nama, st.deskripsi, st.warna, st.urutan, st.is_active, st.created_at, st.updated_at, pst.skill_level
FROM pelayan_service_types pst
JOIN service_types st ON st.id = pst.service_type_id
WHERE pst.pelayan_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

type GetServiceTypesForPelayanRow struct {
	ID         int64   `db:"id" json:"id"`
	ChurchID   int64   `db:"church_id" json:"church_id"`
	Nama       string  `db:"nama" json:"nama"`
	Deskripsi  *string `db:"deskripsi" json:"deskripsi"`
	Warna      *string `db:"warna" json:"warna"`
	Urutan     int64   `db:"urutan" json:"urutan"`
	IsActive   int64   `db:"is_active" json:"is_active"`
	CreatedAt  string  `db:"created_at" json:"created_at"`
	UpdatedAt  string  `db:"updated_at" json:"updated_at"`
	SkillLevel *string `db:"skill_level" json:"skill_level"`
}

func (q *Queries) GetServiceTypesForPelayan(ctx context.Context, pelayanID int64) ([]GetServiceTypesForPelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, getServiceTypesForPelayan, pelayanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetServiceTypesForPelayanRow{}
	for rows.Next() {
		var i GetServiceTypesForPelayanRow
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.Nama,
			&i.Deskripsi,
			&i.Warna,
			&i.Urutan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SkillLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanByChurch = `-- name: ListPelayanByChurch :many
SELECT p.id, p.church_id, p.jemaat_id, p.catatan, p.is_active, p.created_at, p.updated_at, j.nama_lengkap, j.nama_panggilan
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id
WHERE p.church_id = ? AND p.is_active = 1
ORDER BY j.nama_lengkap ASC
LIMIT ? OFFSET ?
`

type ListPelayanByChurchParams struct {
	ChurchID int64 `db:"church_id" json:"church_id"`
	Limit    int64 `db:"limit" json:"limit"`
	Offset   int64 `db:"offset" json:"offset"`
}

type ListPelayanByChurchRow struct {
	ID            int64   `db:"id" json:"id"`
	ChurchID      int64   `db:"church_id" json:"church_id"`
	JemaatID      int64   `db:"jemaat_id" json:"jemaat_id"`
	Catatan       *string `db:"catatan" json:"catatan"`
	IsActive      int64   `db:"is_active" json:"is_active"`
	CreatedAt     string  `db:"created_at" json:"created_at"`
	UpdatedAt     string  `db:"updated_at" json:"updated_at"`
	NamaLengkap   string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan *string `db:"nama_panggilan" json:"nama_panggilan"`
}

func (q *Queries) ListPelayanByChurch(ctx context.Context, arg ListPelayanByChurchParams) ([]ListPelayanByChurchRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanByChurch, arg.ChurchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPelayanByChurchRow{}
	for rows.Next() {
		var i ListPelayanByChurchRow
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.JemaatID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaLengkap,
			&i.NamaPanggilan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPelayan = `-- name: SearchPelayan :many
SELECT p.id, p.church_id, p.jemaat_id, p.catatan, p.is_active, p.created_at, p.updated_at, j.nama_lengkap, j.nama_panggilan
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id
WHERE p.church_id = ? AND p.is_active = 1
  AND (j.nama_lengkap LIKE ? OR j.nama_panggilan LIKE ?)
ORDER BY j.nama_lengkap ASC
LIMIT ? OFFSET ?
`

type SearchPelayanParams struct {
	ChurchID      int64   `db:"church_id" json:"church_id"`
	NamaLengkap   string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan *string `db:"nama_panggilan" json:"nama_panggilan"`
	Limit         int64   `db:"limit" json:"limit"`
	Offset        int64   `db:"offset" json:"offset"`
}

type SearchPelayanRow struct {
	ID            int64   `db:"id" json:"id"`
	ChurchID      int64   `db:"church_id" json:"church_id"`
	JemaatID      int64   `db:"jemaat_id" json:"jemaat_id"`
	Catatan       *string `db:"catatan" json:"catatan"`
	IsActive      int64   `db:"is_active" json:"is_active"`
	CreatedAt     string  `db:"created_at" json:"created_at"`
	UpdatedAt     string  `db:"updated_at" json:"updated_at"`
	NamaLengkap   string  `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan *string `db:"nama_panggilan" json:"nama_panggilan"`
}

func (q *Queries) SearchPelayan(ctx context.Context, arg SearchPelayanParams) ([]SearchPelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPelayan,
		arg.ChurchID,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPelayanRow{}
	for rows.Next() {
		var i SearchPelayanRow
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.JemaatID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaLengkap,
			&i.NamaPanggilan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePelayan = `-- name: UpdatePelayan :one
UPDATE pelayan SET
    catatan = ?,
    is_active = ?,
    updated_at = datetime('now')
WHERE id = ? AND church_id = ?
RETURNING id, church_id, jemaat_id, catatan, is_active, created_at, updated_at
`

type UpdatePelayanParams struct {
	Catatan  *string `db:"catatan" json:"catatan"`
	IsActive int64   `db:"is_active" json:"is_active"`
	ID       int64   `db:"id" json:"id"`
	ChurchID int64   `db:"church_id" json:"church_id"`
}

func (q *Queries) UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, updatePelayan,
		arg.Catatan,
		arg.IsActive,
		arg.ID,
		arg.ChurchID,
	)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.JemaatID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
