// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const getPelayan = `SELECT p.id, p.user_id, p.jemaat_id, p.catatan, p.created_at, p.updated_at, j.nama_lengkap AS jemaat_nama FROM pelayan p JOIN jemaat j ON j.id = p.jemaat_id WHERE p.id = ? AND p.user_id = ?`

type GetPelayanParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetPelayan(ctx context.Context, arg GetPelayanParams) (PelayanRow, error) {
	row := q.db.QueryRowContext(ctx, getPelayan, arg.ID, arg.UserID)
	var p PelayanRow
	err := row.Scan(&p.ID, &p.UserID, &p.JemaatID, &p.Catatan, &p.CreatedAt, &p.UpdatedAt, &p.JemaatNama)
	return p, err
}

const listPelayan = `SELECT p.id, p.user_id, p.jemaat_id, p.catatan, p.created_at, p.updated_at, j.nama_lengkap AS jemaat_nama FROM pelayan p JOIN jemaat j ON j.id = p.jemaat_id WHERE p.user_id = ? ORDER BY j.nama_lengkap ASC`

func (q *Queries) ListPelayan(ctx context.Context, userID int64) ([]PelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayan, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PelayanRow
	for rows.Next() {
		var p PelayanRow
		if err := rows.Scan(&p.ID, &p.UserID, &p.JemaatID, &p.Catatan, &p.CreatedAt, &p.UpdatedAt, &p.JemaatNama); err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	return items, rows.Err()
}

const createPelayan = `INSERT INTO pelayan (user_id, jemaat_id, catatan) VALUES (?, ?, ?) RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at`

type CreatePelayanParams struct {
	UserID   int64
	JemaatID int64
	Catatan  sql.NullString
}

func (q *Queries) CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, createPelayan, arg.UserID, arg.JemaatID, arg.Catatan)
	var p Pelayan
	err := row.Scan(&p.ID, &p.UserID, &p.JemaatID, &p.Catatan, &p.CreatedAt, &p.UpdatedAt)
	return p, err
}

const updatePelayan = `UPDATE pelayan SET catatan=?, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND user_id=? RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at`

type UpdatePelayanParams struct {
	Catatan sql.NullString
	ID      int64
	UserID  int64
}

func (q *Queries) UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, updatePelayan, arg.Catatan, arg.ID, arg.UserID)
	var p Pelayan
	err := row.Scan(&p.ID, &p.UserID, &p.JemaatID, &p.Catatan, &p.CreatedAt, &p.UpdatedAt)
	return p, err
}

const deletePelayan = `DELETE FROM pelayan WHERE id = ? AND user_id = ?`

type DeletePelayanParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePelayan(ctx context.Context, arg DeletePelayanParams) error {
	_, err := q.db.ExecContext(ctx, deletePelayan, arg.ID, arg.UserID)
	return err
}

const getPelayanByJemaat = `SELECT id, user_id, jemaat_id, catatan, created_at, updated_at FROM pelayan WHERE jemaat_id = ? AND user_id = ?`

type GetPelayanByJemaatParams struct {
	JemaatID int64
	UserID   int64
}

func (q *Queries) GetPelayanByJemaat(ctx context.Context, arg GetPelayanByJemaatParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, getPelayanByJemaat, arg.JemaatID, arg.UserID)
	var p Pelayan
	err := row.Scan(&p.ID, &p.UserID, &p.JemaatID, &p.Catatan, &p.CreatedAt, &p.UpdatedAt)
	return p, err
}

const setPelayanServiceTypes = `DELETE FROM pelayan_service_types WHERE pelayan_id = ?`

func (q *Queries) SetPelayanServiceTypes(ctx context.Context, pelayanID int64) error {
	_, err := q.db.ExecContext(ctx, setPelayanServiceTypes, pelayanID)
	return err
}

const addPelayanServiceType = `INSERT INTO pelayan_service_types (pelayan_id, service_type_id) VALUES (?, ?)`

type AddPelayanServiceTypeParams struct {
	PelayanID     int64
	ServiceTypeID int64
}

func (q *Queries) AddPelayanServiceType(ctx context.Context, arg AddPelayanServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, addPelayanServiceType, arg.PelayanID, arg.ServiceTypeID)
	return err
}

const getPelayanServiceTypes = `SELECT st.id, st.user_id, st.nama, st.deskripsi, st.urutan, st.created_at, st.updated_at FROM service_types st JOIN pelayan_service_types pst ON pst.service_type_id = st.id WHERE pst.pelayan_id = ? ORDER BY st.urutan ASC, st.nama ASC`

func (q *Queries) GetPelayanServiceTypes(ctx context.Context, pelayanID int64) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, getPelayanServiceTypes, pelayanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceType
	for rows.Next() {
		var s ServiceType
		if err := rows.Scan(&s.ID, &s.UserID, &s.Nama, &s.Deskripsi, &s.Urutan, &s.CreatedAt, &s.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}
