// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddPelayanServiceType(ctx context.Context, arg AddPelayanServiceTypeParams) error
	ClearPelayanServiceTypes(ctx context.Context, pelayanID int64) error
	CountJadwalByServiceType(ctx context.Context, arg CountJadwalByServiceTypeParams) (int64, error)
	CountJemaatByChurch(ctx context.Context, churchID int64) (int64, error)
	CountKebaktianByChurch(ctx context.Context, arg CountKebaktianByChurchParams) (int64, error)
	CountPelayanByChurch(ctx context.Context, churchID int64) (int64, error)
	CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error)
	CreateJadwalSlot(ctx context.Context, arg CreateJadwalSlotParams) (JadwalPelayanan, error)
	CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error)
	CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error)
	CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error)
	CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error
	DeleteJadwalByKebaktian(ctx context.Context, arg DeleteJadwalByKebaktianParams) error
	DeleteJemaat(ctx context.Context, arg DeleteJemaatParams) error
	DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error
	DeletePelayan(ctx context.Context, arg DeletePelayanParams) error
	DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error
	GetChurchByID(ctx context.Context, id int64) (Church, error)
	GetChurchBySlug(ctx context.Context, slug string) (Church, error)
	GetJadwalByKebaktian(ctx context.Context, arg GetJadwalByKebaktianParams) ([]GetJadwalByKebaktianRow, error)
	GetJemaatByID(ctx context.Context, arg GetJemaatByIDParams) (Jemaat, error)
	GetKebaktianByID(ctx context.Context, arg GetKebaktianByIDParams) (Kebaktian, error)
	GetPelayanByID(ctx context.Context, arg GetPelayanByIDParams) (GetPelayanByIDRow, error)
	GetPelayanByJemaatID(ctx context.Context, arg GetPelayanByJemaatIDParams) (Pelayan, error)
	GetServiceTypeByID(ctx context.Context, arg GetServiceTypeByIDParams) (ServiceType, error)
	GetServiceTypesForPelayan(ctx context.Context, pelayanID int64) ([]GetServiceTypesForPelayanRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListJemaatByChurch(ctx context.Context, arg ListJemaatByChurchParams) ([]Jemaat, error)
	ListKebaktianByChurch(ctx context.Context, arg ListKebaktianByChurchParams) ([]Kebaktian, error)
	ListPelayanByChurch(ctx context.Context, arg ListPelayanByChurchParams) ([]ListPelayanByChurchRow, error)
	ListServiceTypesByChurch(ctx context.Context, churchID int64) ([]ServiceType, error)
	ListUpcomingJadwalForPelayan(ctx context.Context, arg ListUpcomingJadwalForPelayanParams) ([]ListUpcomingJadwalForPelayanRow, error)
	SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error)
	SearchPelayan(ctx context.Context, arg SearchPelayanParams) ([]SearchPelayanRow, error)
	UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error)
	UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error)
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error)
	UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error)
}

var _ Querier = (*Queries)(nil)
