// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddPelayanServiceType(ctx context.Context, arg AddPelayanServiceTypeParams) error
	CountJadwalForServiceType(ctx context.Context, arg CountJadwalForServiceTypeParams) (int64, error)
	CountJemaat(ctx context.Context, userID int64) (int64, error)
	CountKebaktian(ctx context.Context, userID int64) (int64, error)
	CountKeluarga(ctx context.Context, userID int64) (int64, error)
	CountPelayan(ctx context.Context, userID int64) (int64, error)
	CountSearchJemaat(ctx context.Context, arg CountSearchJemaatParams) (int64, error)
	CreateJadwal(ctx context.Context, arg CreateJadwalParams) (JadwalPelayanan, error)
	CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error)
	CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error)
	CreateKeluarga(ctx context.Context, arg CreateKeluargaParams) (Keluarga, error)
	CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error)
	CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteJadwalForKebaktian(ctx context.Context, arg DeleteJadwalForKebaktianParams) error
	DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error
	DeleteKeluarga(ctx context.Context, arg DeleteKeluargaParams) error
	DeletePelayan(ctx context.Context, arg DeletePelayanParams) error
	DeletePelayanServiceTypes(ctx context.Context, pelayanID int64) error
	DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error
	DeleteSession(ctx context.Context, token string) error
	GetJemaat(ctx context.Context, arg GetJemaatParams) (Jemaat, error)
	GetKebaktian(ctx context.Context, arg GetKebaktianParams) (Kebaktian, error)
	GetKeluarga(ctx context.Context, arg GetKeluargaParams) (Keluarga, error)
	GetPelayan(ctx context.Context, arg GetPelayanParams) (Pelayan, error)
	GetPelayanByJemaatID(ctx context.Context, arg GetPelayanByJemaatIDParams) (Pelayan, error)
	GetServiceType(ctx context.Context, arg GetServiceTypeParams) (ServiceType, error)
	GetSession(ctx context.Context, token string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListJadwalForKebaktian(ctx context.Context, arg ListJadwalForKebaktianParams) ([]ListJadwalForKebaktianRow, error)
	ListJadwalForPelayan(ctx context.Context, arg ListJadwalForPelayanParams) ([]ListJadwalForPelayanRow, error)
	ListJemaat(ctx context.Context, arg ListJemaatParams) ([]Jemaat, error)
	ListJemaatByKeluarga(ctx context.Context, arg ListJemaatByKeluargaParams) ([]Jemaat, error)
	ListKebaktian(ctx context.Context, arg ListKebaktianParams) ([]Kebaktian, error)
	ListKebaktianInRange(ctx context.Context, arg ListKebaktianInRangeParams) ([]Kebaktian, error)
	ListKeluarga(ctx context.Context, arg ListKeluargaParams) ([]Keluarga, error)
	ListPelayan(ctx context.Context, arg ListPelayanParams) ([]ListPelayanRow, error)
	ListPelayanForServiceType(ctx context.Context, arg ListPelayanForServiceTypeParams) ([]ListPelayanForServiceTypeRow, error)
	ListPelayanServiceTypes(ctx context.Context, arg ListPelayanServiceTypesParams) ([]ServiceType, error)
	ListServiceTypes(ctx context.Context, userID int64) ([]ServiceType, error)
	SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error)
	UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error)
	UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error)
	UpdateKeluarga(ctx context.Context, arg UpdateKeluargaParams) (Keluarga, error)
	UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error)
	UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
