// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	null "gopkg.in/guregu/null.v4"
)

const addPelayanServiceType = `-- name: AddPelayanServiceType :exec
INSERT INTO pelayan_service_types (pelayan_id, service_type_id)
VALUES (?, ?)
`

type AddPelayanServiceTypeParams struct {
	PelayanID     int64 `db:"pelayan_id" json:"pelayan_id"`
	ServiceTypeID int64 `db:"service_type_id" json:"service_type_id"`
}

func (q *Queries) AddPelayanServiceType(ctx context.Context, arg AddPelayanServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, addPelayanServiceType, arg.PelayanID, arg.ServiceTypeID)
	return err
}

const countJadwalForServiceType = `-- name: CountJadwalForServiceType :one
SELECT COUNT(*) FROM jadwal_pelayanan
WHERE user_id = ? AND service_type_id = ?
`

type CountJadwalForServiceTypeParams struct {
	UserID        int64 `db:"user_id" json:"user_id"`
	ServiceTypeID int64 `db:"service_type_id" json:"service_type_id"`
}

func (q *Queries) CountJadwalForServiceType(ctx context.Context, arg CountJadwalForServiceTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJadwalForServiceType, arg.UserID, arg.ServiceTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countJemaat = `-- name: CountJemaat :one
SELECT COUNT(*) FROM jemaat
WHERE user_id = ? AND is_active = 1
`

func (q *Queries) CountJemaat(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJemaat, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKebaktian = `-- name: CountKebaktian :one
SELECT COUNT(*) FROM kebaktian WHERE user_id = ?
`

func (q *Queries) CountKebaktian(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKebaktian, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKeluarga = `-- name: CountKeluarga :one
SELECT COUNT(*) FROM keluarga WHERE user_id = ?
`

func (q *Queries) CountKeluarga(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countKeluarga, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPelayan = `-- name: CountPelayan :one
SELECT COUNT(*) FROM pelayan WHERE user_id = ?
`

func (q *Queries) CountPelayan(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPelayan, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchJemaat = `-- name: CountSearchJemaat :one
SELECT COUNT(*) FROM jemaat
WHERE user_id = ?1
  AND is_active = 1
  AND (nama_lengkap LIKE ?2
       OR COALESCE(nama_panggilan, '') LIKE ?2
       OR COALESCE(email, '') LIKE ?2)
`

type CountSearchJemaatParams struct {
	UserID  int64  `db:"user_id" json:"user_id"`
	Pattern string `db:"pattern" json:"pattern"`
}

func (q *Queries) CountSearchJemaat(ctx context.Context, arg CountSearchJemaatParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchJemaat, arg.UserID, arg.Pattern)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJadwal = `-- name: CreateJadwal :one
INSERT INTO jadwal_pelayanan (
    user_id, kebaktian_id, service_type_id, pelayan_id, catatan
) VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed, created_at, updated_at
`

type CreateJadwalParams struct {
	UserID        int64       `db:"user_id" json:"user_id"`
	KebaktianID   int64       `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID int64       `db:"service_type_id" json:"service_type_id"`
	PelayanID     null.Int    `db:"pelayan_id" json:"pelayan_id"`
	Catatan       null.String `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateJadwal(ctx context.Context, arg CreateJadwalParams) (JadwalPelayanan, error) {
	row := q.db.QueryRowContext(ctx, createJadwal,
		arg.UserID,
		arg.KebaktianID,
		arg.ServiceTypeID,
		arg.PelayanID,
		arg.Catatan,
	)
	var i JadwalPelayanan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KebaktianID,
		&i.ServiceTypeID,
		&i.PelayanID,
		&i.Catatan,
		&i.Confirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createJemaat = `-- name: CreateJemaat :one
INSERT INTO jemaat (
    user_id, nama_lengkap, nama_panggilan, jenis_kelamin,
    tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email,
    status_pernikahan, tanggal_baptis, tanggal_sidi,
    keluarga_id, catatan
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type CreateJemaatParams struct {
	UserID           int64       `db:"user_id" json:"user_id"`
	NamaLengkap      string      `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    null.String `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     null.String `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     null.String `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      null.String `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           null.String `db:"alamat" json:"alamat"`
	NomorTelepon     null.String `db:"nomor_telepon" json:"nomor_telepon"`
	Email            null.String `db:"email" json:"email"`
	StatusPernikahan null.String `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    null.String `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      null.String `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       null.Int    `db:"keluarga_id" json:"keluarga_id"`
	Catatan          null.String `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateJemaat(ctx context.Context, arg CreateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, createJemaat,
		arg.UserID,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKebaktian = `-- name: CreateKebaktian :one
INSERT INTO kebaktian (user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type CreateKebaktianParams struct {
	UserID      int64       `db:"user_id" json:"user_id"`
	Nama        string      `db:"nama" json:"nama"`
	WaktuMulai  string      `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      null.String `db:"lokasi" json:"lokasi"`
	Tema        null.String `db:"tema" json:"tema"`
	Pengkhotbah null.String `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     null.String `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateKebaktian(ctx context.Context, arg CreateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, createKebaktian,
		arg.UserID,
		arg.Nama,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKeluarga = `-- name: CreateKeluarga :one
INSERT INTO keluarga (user_id, nama_keluarga, alamat, catatan)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type CreateKeluargaParams struct {
	UserID       int64       `db:"user_id" json:"user_id"`
	NamaKeluarga string      `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       null.String `db:"alamat" json:"alamat"`
	Catatan      null.String `db:"catatan" json:"catatan"`
}

func (q *Queries) CreateKeluarga(ctx context.Context, arg CreateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, createKeluarga,
		arg.UserID,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPelayan = `-- name: CreatePelayan :one
INSERT INTO pelayan (user_id, jemaat_id, catatan)
VALUES (?, ?, ?)
RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at
`

type CreatePelayanParams struct {
	UserID   int64       `db:"user_id" json:"user_id"`
	JemaatID int64       `db:"jemaat_id" json:"jemaat_id"`
	Catatan  null.String `db:"catatan" json:"catatan"`
}

func (q *Queries) CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, createPelayan, arg.UserID, arg.JemaatID, arg.Catatan)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceType = `-- name: CreateServiceType :one
INSERT INTO service_types (user_id, nama, deskripsi, urutan)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at
`

type CreateServiceTypeParams struct {
	UserID    int64       `db:"user_id" json:"user_id"`
	Nama      string      `db:"nama" json:"nama"`
	Deskripsi null.String `db:"deskripsi" json:"deskripsi"`
	Urutan    int64       `db:"urutan" json:"urutan"`
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, createServiceType,
		arg.UserID,
		arg.Nama,
		arg.Deskripsi,
		arg.Urutan,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
RETURNING token, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	Token     string `db:"token" json:"token"`
	UserID    int64  `db:"user_id" json:"user_id"`
	ExpiresAt string `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, church_name, timezone)
VALUES (?, ?, ?, ?, ?)
RETURNING id, email, password_hash, display_name, church_name, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `db:"email" json:"email"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
	DisplayName  string `db:"display_name" json:"display_name"`
	ChurchName   string `db:"church_name" json:"church_name"`
	Timezone     string `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.ChurchName,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.ChurchName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateJemaat = `-- name: DeactivateJemaat :exec
UPDATE jemaat
SET is_active = 0,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
`

type DeactivateJemaatParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeactivateJemaat(ctx context.Context, arg DeactivateJemaatParams) error {
	_, err := q.db.ExecContext(ctx, deactivateJemaat, arg.ID, arg.UserID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteJadwalForKebaktian = `-- name: DeleteJadwalForKebaktian :exec
DELETE FROM jadwal_pelayanan
WHERE kebaktian_id = ? AND user_id = ?
`

type DeleteJadwalForKebaktianParams struct {
	KebaktianID int64 `db:"kebaktian_id" json:"kebaktian_id"`
	UserID      int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteJadwalForKebaktian(ctx context.Context, arg DeleteJadwalForKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteJadwalForKebaktian, arg.KebaktianID, arg.UserID)
	return err
}

const deleteKebaktian = `-- name: DeleteKebaktian :exec
DELETE FROM kebaktian WHERE id = ? AND user_id = ?
`

type DeleteKebaktianParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteKebaktian(ctx context.Context, arg DeleteKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteKebaktian, arg.ID, arg.UserID)
	return err
}

const deleteKeluarga = `-- name: DeleteKeluarga :exec
DELETE FROM keluarga WHERE id = ? AND user_id = ?
`

type DeleteKeluargaParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteKeluarga(ctx context.Context, arg DeleteKeluargaParams) error {
	_, err := q.db.ExecContext(ctx, deleteKeluarga, arg.ID, arg.UserID)
	return err
}

const deletePelayan = `-- name: DeletePelayan :exec
DELETE FROM pelayan WHERE id = ? AND user_id = ?
`

type DeletePelayanParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeletePelayan(ctx context.Context, arg DeletePelayanParams) error {
	_, err := q.db.ExecContext(ctx, deletePelayan, arg.ID, arg.UserID)
	return err
}

const deletePelayanServiceTypes = `-- name: DeletePelayanServiceTypes :exec
DELETE FROM pelayan_service_types WHERE pelayan_id = ?
`

func (q *Queries) DeletePelayanServiceTypes(ctx context.Context, pelayanID int64) error {
	_, err := q.db.ExecContext(ctx, deletePelayanServiceTypes, pelayanID)
	return err
}

const deleteServiceType = `-- name: DeleteServiceType :exec
DELETE FROM service_types WHERE id = ? AND user_id = ?
`

type DeleteServiceTypeParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceType, arg.ID, arg.UserID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getJemaat = `-- name: GetJemaat :one
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE id = ? AND user_id = ?
`

type GetJemaatParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetJemaat(ctx context.Context, arg GetJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, getJemaat, arg.ID, arg.UserID)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKebaktian = `-- name: GetKebaktian :one
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian WHERE id = ? AND user_id = ?
`

type GetKebaktianParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetKebaktian(ctx context.Context, arg GetKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, getKebaktian, arg.ID, arg.UserID)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKeluarga = `-- name: GetKeluarga :one
SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga WHERE id = ? AND user_id = ?
`

type GetKeluargaParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetKeluarga(ctx context.Context, arg GetKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, getKeluarga, arg.ID, arg.UserID)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPelayan = `-- name: GetPelayan :one
SELECT id, user_id, jemaat_id, catatan, created_at, updated_at FROM pelayan WHERE id = ? AND user_id = ?
`

type GetPelayanParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetPelayan(ctx context.Context, arg GetPelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, getPelayan, arg.ID, arg.UserID)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPelayanByJemaatID = `-- name: GetPelayanByJemaatID :one
SELECT id, user_id, jemaat_id, catatan, created_at, updated_at FROM pelayan WHERE jemaat_id = ? AND user_id = ?
`

type GetPelayanByJemaatIDParams struct {
	JemaatID int64 `db:"jemaat_id" json:"jemaat_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetPelayanByJemaatID(ctx context.Context, arg GetPelayanByJemaatIDParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, getPelayanByJemaatID, arg.JemaatID, arg.UserID)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceType = `-- name: GetServiceType :one
SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types WHERE id = ? AND user_id = ?
`

type GetServiceTypeParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetServiceType(ctx context.Context, arg GetServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, getServiceType, arg.ID, arg.UserID)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT token, user_id, expires_at, created_at FROM sessions WHERE token = ?
`

func (q *Queries) GetSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, church_name, timezone, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.ChurchName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, church_name, timezone, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.ChurchName,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listJadwalForKebaktian = `-- name: ListJadwalForKebaktian :many
SELECT j.id, j.user_id, j.kebaktian_id, j.service_type_id, j.pelayan_id, j.catatan, j.confirmed, j.created_at, j.updated_at,
       st.nama AS service_type_nama,
       st.urutan AS service_type_urutan,
       p.id AS pelayan_id_real,
       jm.id AS jemaat_id,
       jm.nama_lengkap AS pelayan_nama_lengkap,
       jm.nama_panggilan AS pelayan_nama_panggilan
FROM jadwal_pelayanan j
JOIN service_types st ON st.id = j.service_type_id
LEFT JOIN pelayan p ON p.id = j.pelayan_id
LEFT JOIN jemaat jm ON jm.id = p.jemaat_id
WHERE j.user_id = ? AND j.kebaktian_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

type ListJadwalForKebaktianParams struct {
	UserID      int64 `db:"user_id" json:"user_id"`
	KebaktianID int64 `db:"kebaktian_id" json:"kebaktian_id"`
}

type ListJadwalForKebaktianRow struct {
	ID                   int64       `db:"id" json:"id"`
	UserID               int64       `db:"user_id" json:"user_id"`
	KebaktianID          int64       `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID        int64       `db:"service_type_id" json:"service_type_id"`
	PelayanID            null.Int    `db:"pelayan_id" json:"pelayan_id"`
	Catatan              null.String `db:"catatan" json:"catatan"`
	Confirmed            int64       `db:"confirmed" json:"confirmed"`
	CreatedAt            string      `db:"created_at" json:"created_at"`
	UpdatedAt            string      `db:"updated_at" json:"updated_at"`
	ServiceTypeNama      string      `db:"service_type_nama" json:"service_type_nama"`
	ServiceTypeUrutan    int64       `db:"service_type_urutan" json:"service_type_urutan"`
	PelayanIDReal        null.Int    `db:"pelayan_id_real" json:"pelayan_id_real"`
	JemaatID             null.Int    `db:"jemaat_id" json:"jemaat_id"`
	PelayanNamaLengkap   null.String `db:"pelayan_nama_lengkap" json:"pelayan_nama_lengkap"`
	PelayanNamaPanggilan null.String `db:"pelayan_nama_panggilan" json:"pelayan_nama_panggilan"`
}

func (q *Queries) ListJadwalForKebaktian(ctx context.Context, arg ListJadwalForKebaktianParams) ([]ListJadwalForKebaktianRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalForKebaktian, arg.UserID, arg.KebaktianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJadwalForKebaktianRow{}
	for rows.Next() {
		var i ListJadwalForKebaktianRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KebaktianID,
			&i.ServiceTypeID,
			&i.PelayanID,
			&i.Catatan,
			&i.Confirmed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTypeNama,
			&i.ServiceTypeUrutan,
			&i.PelayanIDReal,
			&i.JemaatID,
			&i.PelayanNamaLengkap,
			&i.PelayanNamaPanggilan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalForPelayan = `-- name: ListJadwalForPelayan :many
SELECT j.id, j.user_id, j.kebaktian_id, j.service_type_id, j.pelayan_id, j.catatan, j.confirmed, j.created_at, j.updated_at,
       k.nama AS kebaktian_nama,
       k.waktu_mulai AS kebaktian_waktu_mulai,
       st.nama AS service_type_nama
FROM jadwal_pelayanan j
JOIN kebaktian k ON k.id = j.kebaktian_id
JOIN service_types st ON st.id = j.service_type_id
WHERE j.user_id = ? AND j.pelayan_id = ?
ORDER BY k.waktu_mulai DESC
`

type ListJadwalForPelayanParams struct {
	UserID    int64    `db:"user_id" json:"user_id"`
	PelayanID null.Int `db:"pelayan_id" json:"pelayan_id"`
}

type ListJadwalForPelayanRow struct {
	ID                  int64       `db:"id" json:"id"`
	UserID              int64       `db:"user_id" json:"user_id"`
	KebaktianID         int64       `db:"kebaktian_id" json:"kebaktian_id"`
	ServiceTypeID       int64       `db:"service_type_id" json:"service_type_id"`
	PelayanID           null.Int    `db:"pelayan_id" json:"pelayan_id"`
	Catatan             null.String `db:"catatan" json:"catatan"`
	Confirmed           int64       `db:"confirmed" json:"confirmed"`
	CreatedAt           string      `db:"created_at" json:"created_at"`
	UpdatedAt           string      `db:"updated_at" json:"updated_at"`
	KebaktianNama       string      `db:"kebaktian_nama" json:"kebaktian_nama"`
	KebaktianWaktuMulai string      `db:"kebaktian_waktu_mulai" json:"kebaktian_waktu_mulai"`
	ServiceTypeNama     string      `db:"service_type_nama" json:"service_type_nama"`
}

func (q *Queries) ListJadwalForPelayan(ctx context.Context, arg ListJadwalForPelayanParams) ([]ListJadwalForPelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalForPelayan, arg.UserID, arg.PelayanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJadwalForPelayanRow{}
	for rows.Next() {
		var i ListJadwalForPelayanRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KebaktianID,
			&i.ServiceTypeID,
			&i.PelayanID,
			&i.Catatan,
			&i.Confirmed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KebaktianNama,
			&i.KebaktianWaktuMulai,
			&i.ServiceTypeNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJemaat = `-- name: ListJemaat :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
LIMIT ? OFFSET ?
`

type ListJemaatParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListJemaat(ctx context.Context, arg ListJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaat, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJemaatByKeluarga = `-- name: ListJemaatByKeluarga :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ? AND keluarga_id = ? AND is_active = 1
ORDER BY nama_lengkap ASC
`

type ListJemaatByKeluargaParams struct {
	UserID     int64    `db:"user_id" json:"user_id"`
	KeluargaID null.Int `db:"keluarga_id" json:"keluarga_id"`
}

func (q *Queries) ListJemaatByKeluarga(ctx context.Context, arg ListJemaatByKeluargaParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, listJemaatByKeluarga, arg.UserID, arg.KeluargaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKebaktian = `-- name: ListKebaktian :many
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian
WHERE user_id = ?
ORDER BY waktu_mulai DESC
LIMIT ? OFFSET ?
`

type ListKebaktianParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListKebaktian(ctx context.Context, arg ListKebaktianParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktian, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kebaktian{}
	for rows.Next() {
		var i Kebaktian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.WaktuMulai,
			&i.Lokasi,
			&i.Tema,
			&i.Pengkhotbah,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKebaktianInRange = `-- name: ListKebaktianInRange :many
SELECT id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at FROM kebaktian
WHERE user_id = ?
  AND waktu_mulai >= ?
  AND waktu_mulai <= ?
ORDER BY waktu_mulai ASC
`

type ListKebaktianInRangeParams struct {
	UserID       int64  `db:"user_id" json:"user_id"`
	WaktuMulai   string `db:"waktu_mulai" json:"waktu_mulai"`
	WaktuMulai_2 string `db:"waktu_mulai_2" json:"waktu_mulai_2"`
}

func (q *Queries) ListKebaktianInRange(ctx context.Context, arg ListKebaktianInRangeParams) ([]Kebaktian, error) {
	rows, err := q.db.QueryContext(ctx, listKebaktianInRange, arg.UserID, arg.WaktuMulai, arg.WaktuMulai_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Kebaktian{}
	for rows.Next() {
		var i Kebaktian
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.WaktuMulai,
			&i.Lokasi,
			&i.Tema,
			&i.Pengkhotbah,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeluarga = `-- name: ListKeluarga :many
SELECT id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at FROM keluarga
WHERE user_id = ?
ORDER BY nama_keluarga ASC
LIMIT ? OFFSET ?
`

type ListKeluargaParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

func (q *Queries) ListKeluarga(ctx context.Context, arg ListKeluargaParams) ([]Keluarga, error) {
	rows, err := q.db.QueryContext(ctx, listKeluarga, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Keluarga{}
	for rows.Next() {
		var i Keluarga
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaKeluarga,
			&i.Alamat,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayan = `-- name: ListPelayan :many
SELECT p.id, p.user_id, p.jemaat_id, p.catatan, p.created_at, p.updated_at, j.nama_lengkap, j.nama_panggilan
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id
WHERE p.user_id = ?
ORDER BY j.nama_lengkap ASC
LIMIT ? OFFSET ?
`

type ListPelayanParams struct {
	UserID int64 `db:"user_id" json:"user_id"`
	Limit  int64 `db:"limit" json:"limit"`
	Offset int64 `db:"offset" json:"offset"`
}

type ListPelayanRow struct {
	ID            int64       `db:"id" json:"id"`
	UserID        int64       `db:"user_id" json:"user_id"`
	JemaatID      int64       `db:"jemaat_id" json:"jemaat_id"`
	Catatan       null.String `db:"catatan" json:"catatan"`
	CreatedAt     string      `db:"created_at" json:"created_at"`
	UpdatedAt     string      `db:"updated_at" json:"updated_at"`
	NamaLengkap   string      `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan null.String `db:"nama_panggilan" json:"nama_panggilan"`
}

func (q *Queries) ListPelayan(ctx context.Context, arg ListPelayanParams) ([]ListPelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayan, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPelayanRow{}
	for rows.Next() {
		var i ListPelayanRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JemaatID,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.NamaLengkap,
			&i.NamaPanggilan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanForServiceType = `-- name: ListPelayanForServiceType :many
SELECT p.id, p.user_id, p.jemaat_id, p.catatan, j.nama_lengkap, j.nama_panggilan
FROM pelayan p
JOIN pelayan_service_types pst ON pst.pelayan_id = p.id
JOIN jemaat j ON j.id = p.jemaat_id
WHERE p.user_id = ? AND pst.service_type_id = ?
ORDER BY j.nama_lengkap ASC
`

type ListPelayanForServiceTypeParams struct {
	UserID        int64 `db:"user_id" json:"user_id"`
	ServiceTypeID int64 `db:"service_type_id" json:"service_type_id"`
}

type ListPelayanForServiceTypeRow struct {
	ID            int64       `db:"id" json:"id"`
	UserID        int64       `db:"user_id" json:"user_id"`
	JemaatID      int64       `db:"jemaat_id" json:"jemaat_id"`
	Catatan       null.String `db:"catatan" json:"catatan"`
	NamaLengkap   string      `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan null.String `db:"nama_panggilan" json:"nama_panggilan"`
}

func (q *Queries) ListPelayanForServiceType(ctx context.Context, arg ListPelayanForServiceTypeParams) ([]ListPelayanForServiceTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanForServiceType, arg.UserID, arg.ServiceTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPelayanForServiceTypeRow{}
	for rows.Next() {
		var i ListPelayanForServiceTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JemaatID,
			&i.Catatan,
			&i.NamaLengkap,
			&i.NamaPanggilan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanServiceTypes = `-- name: ListPelayanServiceTypes :many
SELECT st.id, st.user_id, st.nama, st.deskripsi, st.urutan, st.created_at, st.updated_at
FROM pelayan_service_types pst
JOIN service_types st ON st.id = pst.service_type_id
WHERE pst.pelayan_id = ? AND st.user_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

type ListPelayanServiceTypesParams struct {
	PelayanID int64 `db:"pelayan_id" json:"pelayan_id"`
	UserID    int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) ListPelayanServiceTypes(ctx context.Context, arg ListPelayanServiceTypesParams) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanServiceTypes, arg.PelayanID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.Deskripsi,
			&i.Urutan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types
WHERE user_id = ?
ORDER BY urutan ASC, nama ASC
`

func (q *Queries) ListServiceTypes(ctx context.Context, userID int64) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.Deskripsi,
			&i.Urutan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJemaat = `-- name: SearchJemaat :many
SELECT id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at FROM jemaat
WHERE user_id = ?1
  AND is_active = 1
  AND (nama_lengkap LIKE ?2
       OR COALESCE(nama_panggilan, '') LIKE ?2
       OR COALESCE(email, '') LIKE ?2)
ORDER BY nama_lengkap ASC
LIMIT ?4 OFFSET ?3
`

type SearchJemaatParams struct {
	UserID  int64  `db:"user_id" json:"user_id"`
	Pattern string `db:"pattern" json:"pattern"`
	Off     int64  `db:"off" json:"off"`
	Lim     int64  `db:"lim" json:"lim"`
}

func (q *Queries) SearchJemaat(ctx context.Context, arg SearchJemaatParams) ([]Jemaat, error) {
	rows, err := q.db.QueryContext(ctx, searchJemaat,
		arg.UserID,
		arg.Pattern,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Jemaat{}
	for rows.Next() {
		var i Jemaat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.NamaLengkap,
			&i.NamaPanggilan,
			&i.JenisKelamin,
			&i.TanggalLahir,
			&i.TempatLahir,
			&i.Alamat,
			&i.NomorTelepon,
			&i.Email,
			&i.StatusPernikahan,
			&i.TanggalBaptis,
			&i.TanggalSidi,
			&i.KeluargaID,
			&i.Catatan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJemaat = `-- name: UpdateJemaat :one
UPDATE jemaat SET
    nama_lengkap = ?, nama_panggilan = ?, jenis_kelamin = ?,
    tanggal_lahir = ?, tempat_lahir = ?, alamat = ?,
    nomor_telepon = ?, email = ?, status_pernikahan = ?,
    tanggal_baptis = ?, tanggal_sidi = ?, keluarga_id = ?,
    catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama_lengkap, nama_panggilan, jenis_kelamin, tanggal_lahir, tempat_lahir, alamat, nomor_telepon, email, status_pernikahan, tanggal_baptis, tanggal_sidi, keluarga_id, catatan, is_active, created_at, updated_at
`

type UpdateJemaatParams struct {
	NamaLengkap      string      `db:"nama_lengkap" json:"nama_lengkap"`
	NamaPanggilan    null.String `db:"nama_panggilan" json:"nama_panggilan"`
	JenisKelamin     null.String `db:"jenis_kelamin" json:"jenis_kelamin"`
	TanggalLahir     null.String `db:"tanggal_lahir" json:"tanggal_lahir"`
	TempatLahir      null.String `db:"tempat_lahir" json:"tempat_lahir"`
	Alamat           null.String `db:"alamat" json:"alamat"`
	NomorTelepon     null.String `db:"nomor_telepon" json:"nomor_telepon"`
	Email            null.String `db:"email" json:"email"`
	StatusPernikahan null.String `db:"status_pernikahan" json:"status_pernikahan"`
	TanggalBaptis    null.String `db:"tanggal_baptis" json:"tanggal_baptis"`
	TanggalSidi      null.String `db:"tanggal_sidi" json:"tanggal_sidi"`
	KeluargaID       null.Int    `db:"keluarga_id" json:"keluarga_id"`
	Catatan          null.String `db:"catatan" json:"catatan"`
	ID               int64       `db:"id" json:"id"`
	UserID           int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateJemaat(ctx context.Context, arg UpdateJemaatParams) (Jemaat, error) {
	row := q.db.QueryRowContext(ctx, updateJemaat,
		arg.NamaLengkap,
		arg.NamaPanggilan,
		arg.JenisKelamin,
		arg.TanggalLahir,
		arg.TempatLahir,
		arg.Alamat,
		arg.NomorTelepon,
		arg.Email,
		arg.StatusPernikahan,
		arg.TanggalBaptis,
		arg.TanggalSidi,
		arg.KeluargaID,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Jemaat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaLengkap,
		&i.NamaPanggilan,
		&i.JenisKelamin,
		&i.TanggalLahir,
		&i.TempatLahir,
		&i.Alamat,
		&i.NomorTelepon,
		&i.Email,
		&i.StatusPernikahan,
		&i.TanggalBaptis,
		&i.TanggalSidi,
		&i.KeluargaID,
		&i.Catatan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKebaktian = `-- name: UpdateKebaktian :one
UPDATE kebaktian SET
    nama = ?, waktu_mulai = ?, lokasi = ?, tema = ?,
    pengkhotbah = ?, catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama, waktu_mulai, lokasi, tema, pengkhotbah, catatan, created_at, updated_at
`

type UpdateKebaktianParams struct {
	Nama        string      `db:"nama" json:"nama"`
	WaktuMulai  string      `db:"waktu_mulai" json:"waktu_mulai"`
	Lokasi      null.String `db:"lokasi" json:"lokasi"`
	Tema        null.String `db:"tema" json:"tema"`
	Pengkhotbah null.String `db:"pengkhotbah" json:"pengkhotbah"`
	Catatan     null.String `db:"catatan" json:"catatan"`
	ID          int64       `db:"id" json:"id"`
	UserID      int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateKebaktian(ctx context.Context, arg UpdateKebaktianParams) (Kebaktian, error) {
	row := q.db.QueryRowContext(ctx, updateKebaktian,
		arg.Nama,
		arg.WaktuMulai,
		arg.Lokasi,
		arg.Tema,
		arg.Pengkhotbah,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Kebaktian
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.WaktuMulai,
		&i.Lokasi,
		&i.Tema,
		&i.Pengkhotbah,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKeluarga = `-- name: UpdateKeluarga :one
UPDATE keluarga SET
    nama_keluarga = ?, alamat = ?, catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama_keluarga, alamat, catatan, created_at, updated_at
`

type UpdateKeluargaParams struct {
	NamaKeluarga string      `db:"nama_keluarga" json:"nama_keluarga"`
	Alamat       null.String `db:"alamat" json:"alamat"`
	Catatan      null.String `db:"catatan" json:"catatan"`
	ID           int64       `db:"id" json:"id"`
	UserID       int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateKeluarga(ctx context.Context, arg UpdateKeluargaParams) (Keluarga, error) {
	row := q.db.QueryRowContext(ctx, updateKeluarga,
		arg.NamaKeluarga,
		arg.Alamat,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Keluarga
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NamaKeluarga,
		&i.Alamat,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePelayan = `-- name: UpdatePelayan :one
UPDATE pelayan SET
    catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at
`

type UpdatePelayanParams struct {
	Catatan null.String `db:"catatan" json:"catatan"`
	ID      int64       `db:"id" json:"id"`
	UserID  int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, updatePelayan, arg.Catatan, arg.ID, arg.UserID)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceType = `-- name: UpdateServiceType :one
UPDATE service_types SET
    nama = ?, deskripsi = ?, urutan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at
`

type UpdateServiceTypeParams struct {
	Nama      string      `db:"nama" json:"nama"`
	Deskripsi null.String `db:"deskripsi" json:"deskripsi"`
	Urutan    int64       `db:"urutan" json:"urutan"`
	ID        int64       `db:"id" json:"id"`
	UserID    int64       `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, updateServiceType,
		arg.Nama,
		arg.Deskripsi,
		arg.Urutan,
		arg.ID,
		arg.UserID,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET
    password_hash = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `db:"password_hash" json:"password_hash"`
	ID           int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
