// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: servicetypes.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countJadwalByServiceType = `-- name: CountJadwalByServiceType :one
SELECT COUNT(*) FROM jadwal_pelayanan
WHERE service_type_id = ? AND user_id = ?
`

type CountJadwalByServiceTypeParams struct {
	ServiceTypeID int64 `json:"service_type_id"`
	UserID        int64 `json:"user_id"`
}

func (q *Queries) CountJadwalByServiceType(ctx context.Context, arg CountJadwalByServiceTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJadwalByServiceType, arg.ServiceTypeID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceType = `-- name: CreateServiceType :one
INSERT INTO service_types (user_id, nama, deskripsi, urutan)
VALUES (?, ?, ?, ?) RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at
`

type CreateServiceTypeParams struct {
	UserID    int64          `json:"user_id"`
	Nama      string         `json:"nama"`
	Deskripsi sql.NullString `json:"deskripsi"`
	Urutan    int64          `json:"urutan"`
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, createServiceType,
		arg.UserID,
		arg.Nama,
		arg.Deskripsi,
		arg.Urutan,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceType = `-- name: DeleteServiceType :exec
DELETE FROM service_types WHERE id = ? AND user_id = ?
`

type DeleteServiceTypeParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceType, arg.ID, arg.UserID)
	return err
}

const getServiceType = `-- name: GetServiceType :one
SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types WHERE id = ? AND user_id = ?
`

type GetServiceTypeParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetServiceType(ctx context.Context, arg GetServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, getServiceType, arg.ID, arg.UserID)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceTypes = `-- name: ListServiceTypes :many
SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types
WHERE user_id = ?
ORDER BY urutan ASC, nama ASC
`

func (q *Queries) ListServiceTypes(ctx context.Context, userID int64) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nama,
			&i.Deskripsi,
			&i.Urutan,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceType = `-- name: UpdateServiceType :one
UPDATE service_types SET
    nama = ?, deskripsi = ?, urutan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at
`

type UpdateServiceTypeParams struct {
	Nama      string         `json:"nama"`
	Deskripsi sql.NullString `json:"deskripsi"`
	Urutan    int64          `json:"urutan"`
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, updateServiceType,
		arg.Nama,
		arg.Deskripsi,
		arg.Urutan,
		arg.ID,
		arg.UserID,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nama,
		&i.Deskripsi,
		&i.Urutan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
