// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_types.sql

package sqlc

import (
	"context"
)

const createServiceType = `-- name: CreateServiceType :one
INSERT INTO service_types (church_id, nama, deskripsi, warna, urutan)
VALUES (?, ?, ?, ?, ?)
RETURNING id, church_id, nama, deskripsi, warna, urutan, is_active, created_at, updated_at
`

type CreateServiceTypeParams struct {
	ChurchID  int64   `db:"church_id" json:"church_id"`
	Nama      string  `db:"nama" json:"nama"`
	Deskripsi *string `db:"deskripsi" json:"deskripsi"`
	Warna     *string `db:"warna" json:"warna"`
	Urutan    int64   `db:"urutan" json:"urutan"`
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, createServiceType,
		arg.ChurchID,
		arg.Nama,
		arg.Deskripsi,
		arg.Warna,
		arg.Urutan,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Deskripsi,
		&i.Warna,
		&i.Urutan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceType = `-- name: DeleteServiceType :exec
DELETE FROM service_types WHERE id = ? AND church_id = ?
`

type DeleteServiceTypeParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceType, arg.ID, arg.ChurchID)
	return err
}

const getServiceTypeByID = `-- name: GetServiceTypeByID :one
SELECT id, church_id, nama, deskripsi, warna, urutan, is_active, created_at, updated_at FROM service_types WHERE id = ? AND church_id = ?
`

type GetServiceTypeByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	ChurchID int64 `db:"church_id" json:"church_id"`
}

func (q *Queries) GetServiceTypeByID(ctx context.Context, arg GetServiceTypeByIDParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, getServiceTypeByID, arg.ID, arg.ChurchID)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Deskripsi,
		&i.Warna,
		&i.Urutan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceTypesByChurch = `-- name: ListServiceTypesByChurch :many
SELECT id, church_id, nama, deskripsi, warna, urutan, is_active, created_at, updated_at FROM service_types
WHERE church_id = ? AND is_active = 1
ORDER BY urutan ASC, nama ASC
`

func (q *Queries) ListServiceTypesByChurch(ctx context.Context, churchID int64) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTypesByChurch, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceType{}
	for rows.Next() {
		var i ServiceType
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.Nama,
			&i.Deskripsi,
			&i.Warna,
			&i.Urutan,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceType = `-- name: UpdateServiceType :one
UPDATE service_types SET
    nama = ?,
    deskripsi = ?,
    warna = ?,
    urutan = ?,
    updated_at = datetime('now')
WHERE id = ? AND church_id = ?
RETURNING id, church_id, nama, deskripsi, warna, urutan, is_active, created_at, updated_at
`

type UpdateServiceTypeParams struct {
	Nama      string  `db:"nama" json:"nama"`
	Deskripsi *string `db:"deskripsi" json:"deskripsi"`
	Warna     *string `db:"warna" json:"warna"`
	Urutan    int64   `db:"urutan" json:"urutan"`
	ID        int64   `db:"id" json:"id"`
	ChurchID  int64   `db:"church_id" json:"church_id"`
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, updateServiceType,
		arg.Nama,
		arg.Deskripsi,
		arg.Warna,
		arg.Urutan,
		arg.ID,
		arg.ChurchID,
	)
	var i ServiceType
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.Nama,
		&i.Deskripsi,
		&i.Warna,
		&i.Urutan,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
