// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
	"database/sql"
)

const getServiceType = `SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types WHERE id = ? AND user_id = ?`

type GetServiceTypeParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetServiceType(ctx context.Context, arg GetServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, getServiceType, arg.ID, arg.UserID)
	var s ServiceType
	err := row.Scan(&s.ID, &s.UserID, &s.Nama, &s.Deskripsi, &s.Urutan, &s.CreatedAt, &s.UpdatedAt)
	return s, err
}

const listServiceTypes = `SELECT id, user_id, nama, deskripsi, urutan, created_at, updated_at FROM service_types WHERE user_id = ? ORDER BY urutan ASC, nama ASC`

func (q *Queries) ListServiceTypes(ctx context.Context, userID int64) ([]ServiceType, error) {
	rows, err := q.db.QueryContext(ctx, listServiceTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceType
	for rows.Next() {
		var s ServiceType
		if err := rows.Scan(&s.ID, &s.UserID, &s.Nama, &s.Deskripsi, &s.Urutan, &s.CreatedAt, &s.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}

const createServiceType = `INSERT INTO service_types (user_id, nama, deskripsi, urutan) VALUES (?, ?, ?, ?) RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at`

type CreateServiceTypeParams struct {
	UserID    int64
	Nama      string
	Deskripsi sql.NullString
	Urutan    int64
}

func (q *Queries) CreateServiceType(ctx context.Context, arg CreateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, createServiceType, arg.UserID, arg.Nama, arg.Deskripsi, arg.Urutan)
	var s ServiceType
	err := row.Scan(&s.ID, &s.UserID, &s.Nama, &s.Deskripsi, &s.Urutan, &s.CreatedAt, &s.UpdatedAt)
	return s, err
}

const updateServiceType = `UPDATE service_types SET nama=?, deskripsi=?, urutan=?, updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=? AND user_id=? RETURNING id, user_id, nama, deskripsi, urutan, created_at, updated_at`

type UpdateServiceTypeParams struct {
	Nama      string
	Deskripsi sql.NullString
	Urutan    int64
	ID        int64
	UserID    int64
}

func (q *Queries) UpdateServiceType(ctx context.Context, arg UpdateServiceTypeParams) (ServiceType, error) {
	row := q.db.QueryRowContext(ctx, updateServiceType, arg.Nama, arg.Deskripsi, arg.Urutan, arg.ID, arg.UserID)
	var s ServiceType
	err := row.Scan(&s.ID, &s.UserID, &s.Nama, &s.Deskripsi, &s.Urutan, &s.CreatedAt, &s.UpdatedAt)
	return s, err
}

const deleteServiceType = `DELETE FROM service_types WHERE id = ? AND user_id = ?`

type DeleteServiceTypeParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteServiceType(ctx context.Context, arg DeleteServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, deleteServiceType, arg.ID, arg.UserID)
	return err
}
