// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jadwal.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createJadwal = `-- name: CreateJadwal :one
INSERT INTO jadwal_pelayanan (user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed)
VALUES (?, ?, ?, ?, ?, ?) RETURNING id, user_id, kebaktian_id, service_type_id, pelayan_id, catatan, confirmed, created_at, updated_at
`

type CreateJadwalParams struct {
	UserID        int64          `json:"user_id"`
	KebaktianID   int64          `json:"kebaktian_id"`
	ServiceTypeID int64          `json:"service_type_id"`
	PelayanID     sql.NullInt64  `json:"pelayan_id"`
	Catatan       sql.NullString `json:"catatan"`
	Confirmed     int64          `json:"confirmed"`
}

func (q *Queries) CreateJadwal(ctx context.Context, arg CreateJadwalParams) (JadwalPelayanan, error) {
	row := q.db.QueryRowContext(ctx, createJadwal,
		arg.UserID,
		arg.KebaktianID,
		arg.ServiceTypeID,
		arg.PelayanID,
		arg.Catatan,
		arg.Confirmed,
	)
	var i JadwalPelayanan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KebaktianID,
		&i.ServiceTypeID,
		&i.PelayanID,
		&i.Catatan,
		&i.Confirmed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteJadwalByKebaktian = `-- name: DeleteJadwalByKebaktian :exec
DELETE FROM jadwal_pelayanan WHERE kebaktian_id = ? AND user_id = ?
`

type DeleteJadwalByKebaktianParams struct {
	KebaktianID int64 `json:"kebaktian_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteJadwalByKebaktian(ctx context.Context, arg DeleteJadwalByKebaktianParams) error {
	_, err := q.db.ExecContext(ctx, deleteJadwalByKebaktian, arg.KebaktianID, arg.UserID)
	return err
}

const listJadwalByKebaktian = `-- name: ListJadwalByKebaktian :many
SELECT jp.id, jp.user_id, jp.kebaktian_id, jp.service_type_id, jp.pelayan_id, jp.catatan, jp.confirmed, jp.created_at, jp.updated_at, st.nama AS service_type_nama, j.nama_lengkap AS pelayan_nama
FROM jadwal_pelayanan jp
JOIN service_types st ON st.id = jp.service_type_id AND st.user_id = jp.user_id
LEFT JOIN pelayan p ON p.id = jp.pelayan_id AND p.user_id = jp.user_id
LEFT JOIN jemaat j ON j.id = p.jemaat_id AND j.user_id = jp.user_id
WHERE jp.kebaktian_id = ? AND jp.user_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

type ListJadwalByKebaktianParams struct {
	KebaktianID int64 `json:"kebaktian_id"`
	UserID      int64 `json:"user_id"`
}

type ListJadwalByKebaktianRow struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	KebaktianID     int64          `json:"kebaktian_id"`
	ServiceTypeID   int64          `json:"service_type_id"`
	PelayanID       sql.NullInt64  `json:"pelayan_id"`
	Catatan         sql.NullString `json:"catatan"`
	Confirmed       int64          `json:"confirmed"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	ServiceTypeNama string         `json:"service_type_nama"`
	PelayanNama     sql.NullString `json:"pelayan_nama"`
}

func (q *Queries) ListJadwalByKebaktian(ctx context.Context, arg ListJadwalByKebaktianParams) ([]ListJadwalByKebaktianRow, error) {
	rows, err := q.db.QueryContext(ctx, listJadwalByKebaktian, arg.KebaktianID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJadwalByKebaktianRow{}
	for rows.Next() {
		var i ListJadwalByKebaktianRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.KebaktianID,
			&i.ServiceTypeID,
			&i.PelayanID,
			&i.Catatan,
			&i.Confirmed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceTypeNama,
			&i.PelayanNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
