// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pelayan.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPelayan = `-- name: CreatePelayan :one
INSERT INTO pelayan (user_id, jemaat_id, catatan)
VALUES (?, ?, ?) RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at
`

type CreatePelayanParams struct {
	UserID   int64          `json:"user_id"`
	JemaatID int64          `json:"jemaat_id"`
	Catatan  sql.NullString `json:"catatan"`
}

func (q *Queries) CreatePelayan(ctx context.Context, arg CreatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, createPelayan, arg.UserID, arg.JemaatID, arg.Catatan)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePelayan = `-- name: DeletePelayan :exec
DELETE FROM pelayan WHERE id = ? AND user_id = ?
`

type DeletePelayanParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeletePelayan(ctx context.Context, arg DeletePelayanParams) error {
	_, err := q.db.ExecContext(ctx, deletePelayan, arg.ID, arg.UserID)
	return err
}

const deletePelayanServiceTypes = `-- name: DeletePelayanServiceTypes :exec
DELETE FROM pelayan_service_types WHERE pelayan_id = ?
`

func (q *Queries) DeletePelayanServiceTypes(ctx context.Context, pelayanID int64) error {
	_, err := q.db.ExecContext(ctx, deletePelayanServiceTypes, pelayanID)
	return err
}

const getPelayan = `-- name: GetPelayan :one
SELECT id, user_id, jemaat_id, catatan, created_at, updated_at FROM pelayan WHERE id = ? AND user_id = ?
`

type GetPelayanParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetPelayan(ctx context.Context, arg GetPelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, getPelayan, arg.ID, arg.UserID)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPelayanServiceType = `-- name: InsertPelayanServiceType :exec
INSERT INTO pelayan_service_types (pelayan_id, service_type_id)
VALUES (?, ?)
`

type InsertPelayanServiceTypeParams struct {
	PelayanID     int64 `json:"pelayan_id"`
	ServiceTypeID int64 `json:"service_type_id"`
}

func (q *Queries) InsertPelayanServiceType(ctx context.Context, arg InsertPelayanServiceTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertPelayanServiceType, arg.PelayanID, arg.ServiceTypeID)
	return err
}

const listPelayan = `-- name: ListPelayan :many
SELECT p.id, p.user_id, p.jemaat_id, p.catatan, p.created_at, p.updated_at, j.nama_lengkap AS jemaat_nama
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id AND j.user_id = p.user_id
WHERE p.user_id = ?
ORDER BY j.nama_lengkap ASC
`

type ListPelayanRow struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	JemaatID   int64          `json:"jemaat_id"`
	Catatan    sql.NullString `json:"catatan"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
	JemaatNama string         `json:"jemaat_nama"`
}

func (q *Queries) ListPelayan(ctx context.Context, userID int64) ([]ListPelayanRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayan, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPelayanRow{}
	for rows.Next() {
		var i ListPelayanRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.JemaatID,
			&i.Catatan,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JemaatNama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanForAllServiceTypes = `-- name: ListPelayanForAllServiceTypes :many
SELECT pst.service_type_id, p.id, j.nama_lengkap AS jemaat_nama
FROM pelayan p
JOIN jemaat j ON j.id = p.jemaat_id AND j.user_id = p.user_id
JOIN pelayan_service_types pst ON pst.pelayan_id = p.id
WHERE p.user_id = ?
ORDER BY pst.service_type_id ASC, j.nama_lengkap ASC
`

type ListPelayanForAllServiceTypesRow struct {
	ServiceTypeID int64  `json:"service_type_id"`
	ID            int64  `json:"id"`
	JemaatNama    string `json:"jemaat_nama"`
}

func (q *Queries) ListPelayanForAllServiceTypes(ctx context.Context, userID int64) ([]ListPelayanForAllServiceTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanForAllServiceTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPelayanForAllServiceTypesRow{}
	for rows.Next() {
		var i ListPelayanForAllServiceTypesRow
		if err := rows.Scan(&i.ServiceTypeID, &i.ID, &i.JemaatNama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanServiceTypeIDs = `-- name: ListPelayanServiceTypeIDs :many
SELECT service_type_id FROM pelayan_service_types
WHERE pelayan_id = ?
`

func (q *Queries) ListPelayanServiceTypeIDs(ctx context.Context, pelayanID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanServiceTypeIDs, pelayanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var service_type_id int64
		if err := rows.Scan(&service_type_id); err != nil {
			return nil, err
		}
		items = append(items, service_type_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPelayanServiceTypeNames = `-- name: ListPelayanServiceTypeNames :many
SELECT st.nama
FROM pelayan_service_types pst
JOIN service_types st ON st.id = pst.service_type_id
WHERE pst.pelayan_id = ?
ORDER BY st.urutan ASC, st.nama ASC
`

func (q *Queries) ListPelayanServiceTypeNames(ctx context.Context, pelayanID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPelayanServiceTypeNames, pelayanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var nama string
		if err := rows.Scan(&nama); err != nil {
			return nil, err
		}
		items = append(items, nama)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePelayan = `-- name: UpdatePelayan :one
UPDATE pelayan SET
    jemaat_id = ?, catatan = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = ? AND user_id = ?
RETURNING id, user_id, jemaat_id, catatan, created_at, updated_at
`

type UpdatePelayanParams struct {
	JemaatID int64          `json:"jemaat_id"`
	Catatan  sql.NullString `json:"catatan"`
	ID       int64          `json:"id"`
	UserID   int64          `json:"user_id"`
}

func (q *Queries) UpdatePelayan(ctx context.Context, arg UpdatePelayanParams) (Pelayan, error) {
	row := q.db.QueryRowContext(ctx, updatePelayan,
		arg.JemaatID,
		arg.Catatan,
		arg.ID,
		arg.UserID,
	)
	var i Pelayan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.JemaatID,
		&i.Catatan,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
